includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased_full.yaml
- ../configs/evaluation/line2_gaplock_eval_curriculum.yaml
- ../configs/wandb.yaml
experiment:
  name: a2c
  episodes: 1500
  seed: 42
environment:
  action_repeat: 2
  max_steps: 2500
agents:
  car_0:
    role: attacker
    algorithm: sb3_a2c
    target_id: car_1
    params:
      learning_rate: 0.0003
      gamma: 0.995
      n_steps: 5
      gae_lambda: 1.0
      ent_coef: 0.0
      vf_coef: 0.5
      hidden_dims:
      - 256
      - 256
    observation:
      preset: gaplock
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - a2c
  - comparison
  - gaplock
  notes: "A2C comparison for gaplock adversarial task (use run_sb3.py)"
  mode: online
