meta:
  name: gaplock_td3

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 1500
    lidar_beams: 54
    terminate_on_any_done: true
    vehicle_params:
      v_max: 0.8
      v_min: 0.001
    spawn_points:
      - spawn_1
      - spawn_2
    spawn_point_sets:
      - id: offset_lane_a
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_1
          - spawn_3
      - id: offset_lane_b
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_1
          - spawn_5
      - id: extended_gap
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_1
          - spawn_6
    spawn_curriculum:
      min_episode: 600
      activation_samples: 150
      success_window: 200
      enable_rate: 0.72
      enable_patience: 3
      disable_rate: 0.55
      disable_patience: 2
      cooldown: 180
      persist: false
    #   min_episode: 1000
    #   success_window: 200
    #   enable_rate: 0.7
    #   enable_patience: 3
    #   disable_rate: 0.5
    #   disable_patience: 2
    #   cooldown: 200

  main:
    mode: train_eval
    train_episodes: 5000
    eval_episodes: 5
    eval_interval: 10
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/td3_gaplock_v2/td3_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: td3
      tags:
        - td3

  agents:
    car_0:
      trainable: true
      algorithm:
        name: td3
        params:
          device: cpu
          actor_lr: 0.00025
          critic_lr: 0.0005
          gamma: 0.99
          tau: 0.005
          policy_noise: 0.2
          noise_clip: 0.4
          policy_delay: 2
          batch_size: 256
          buffer_size: 200000
          warmup_steps: 8000
          updates_per_step: 1
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.5
          per_beta: 0.5
          per_beta_increment: 0.000005
          per_min_priority: 0.0001
          per_epsilon: 0.000001
          exploration_noise: 0.28
          exploration_noise_final: 0.12
          exploration_noise_decay_steps: 400000
          exploration_noise_decay_episodes: 0
          initial_speed: 0.2
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          hidden_dims:
            - 256
            - 256
            - 128
          save_dir: checkpoints/td3_gaplock_v2
          checkpoint_name: td3_gaplock.pt
      reward:
        task: gaplock
        idle_speed_threshold: 0.02
        idle_patience_steps: 90
        features:
          - gaplock_offense
          - idle_guard
        params:
          target_crash_reward: 60.0
          self_collision_penalty: -10.0
          reward_weight: null
          reward_decay: null
          reward_smoothing: null
          step_reward: 0.015
          idle_speed_threshold: 0.02
          idle_penalty: -0.08
          idle_penalty_steps: 8
          idle_truncation_penalty: -35.0
          pressure_distance: 1.1
          pressure_timeout: 0.8
          pressure_min_speed: 0.2
          pressure_bonus: 0.25
          pressure_bonus_interval: 5
          proximity_penalty_distance: 2.0
          proximity_penalty_value: -0.05
          speed_bonus_coef: 0.012
          speed_bonus_target: 4.0
          brake_penalty: -0.07
          brake_speed_threshold: 1.2
          brake_drop_threshold: 0.5
          heading_reward_coef: 0.02
          distance_reward_near: 0.18
          distance_reward_near_distance: 0.9
          distance_reward_far_distance: 2.2
          distance_penalty_far: 0.35
          pressure_streak_bonus: 0.1
          pressure_streak_cap: 6
          commit_distance: 0.75
          commit_heading_threshold: 0.65
          commit_speed_threshold: 1.8
          commit_bonus: 3.5
          escape_distance: 3.2
          escape_penalty: 3.5
          relative_reward:
            weights:
              front: 0.03
              front_right: 0.025
              right: 0.015
              back_right: -0.015
              back: -0.025
              back_left: -0.015
              left: 0.015
              front_left: 0.025
            preferred_radius: 0.9
            inner_tolerance: 0.3
            outer_tolerance: 0.1
            ignored_agents:
              - car_1
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_velocity
                type: velocity
                params:
                  normalize: 10.0
                  include_speed: true
                  speed_scale: 10.0
              - id: ego_collision
                type: collision
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: relative_sector
                type: relative_sector
                params:
                  preferred_radius: 0.7
                  inner_tolerance: 0.1
                  outer_tolerance: 0.2
                target:
                  agent: car_1
              - id: target_collision
                type: collision
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          mode: secondary
          max_speed: 1.8
          min_speed: 0.0
          steering_gain: 1.0
          bubble_radius: 2.0
          steer_smooth: 0.0
          secondary_warning_border: 0.35
          secondary_hard_border: 0.5
          secondary_safe_distance: 1.0
          secondary_turn_gain: 1.5
          secondary_border_speed_scale: 0.5
          secondary_max_turn: 1.0
          secondary_target_agent: car_0
      defender_curriculum:
        min_episode: 3000
        success_window: 200
        activation_samples: 200
        enable_patience: 4
        disable_patience: 2
        cooldown: 300
        persist: false
        stages:
          - name: baseline
            params:
              mode: secondary
              max_speed: 0.8
              min_speed: 0.0
              steering_gain: 1.0
              bubble_radius: 2.0
              steer_smooth: 0.0
              secondary_warning_border: 0.35
              secondary_hard_border: 0.5
              secondary_safe_distance: 1.0
              secondary_turn_gain: 1.5
              secondary_border_speed_scale: 0.5
              secondary_max_turn: 1.0
              secondary_target_agent: car_0
          - name: pressure
            enable_rate: 0.6
            disable_rate: 0.5
            params:
              mode: secondary
              max_speed: 1.0
              min_speed: 0.0
              steering_gain: 1.0
              bubble_radius: 2.0
              steer_smooth: 0.0
              secondary_warning_border: 0.35
              secondary_hard_border: 0.5
              secondary_safe_distance: 1.0
              secondary_turn_gain: 1.5
              secondary_border_speed_scale: 0.5
              secondary_max_turn: 1.0
              secondary_target_agent: car_0
          - name: aggressive
            enable_rate: 0.75
            disable_rate: 0.6
            params:
              mode: secondary
              max_speed: 1.1
              min_speed: 0.0
              steering_gain: 1.0
              bubble_radius: 2.0
              steer_smooth: 0.0
              secondary_warning_border: 0.35
              secondary_hard_border: 0.5
              secondary_safe_distance: 1.0
              secondary_turn_gain: 1.5
              secondary_border_speed_scale: 0.5
              secondary_max_turn: 1.0
              secondary_target_agent: car_0
          - name: lockdown
            enable_rate: 0.85
            disable_rate: 0.7
            params:
              mode: secondary
              max_speed: 1.2
              min_speed: 0.0
              steering_gain: 1.0
              bubble_radius: 2.0
              steer_smooth: 0.0
              secondary_warning_border: 0.35
              secondary_hard_border: 0.5
              secondary_safe_distance: 1.0
              secondary_turn_gain: 1.5
              secondary_border_speed_scale: 0.5
              secondary_max_turn: 1.0
              secondary_target_agent: car_0
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
