meta:
  name: gaplock_ppo

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 5000
    lidar_beams: 720
    terminate_on_any_done: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
      s_min: -0.46
      s_max: 0.46
    spawn_points:
      - spawn_2
      - spawn_1

  main:
    mode: train
    train_episodes: 15000
    # eval_episodes: 10
    # eval_interval: 150
    # federated:
    #   enabled: false
    #   interval: 50
    #   agents:
    #     - car_0
    #   root: outputs/federated_gaplock
    #   mode: mean
    #   timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/ppo_gaplock/ppo_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: gaplock_ppo
      tags:
        - ppo

  agents:
    car_0:
      trainable: true
      role: attacker
      algorithm:
        name: ppo
        params:
          device: cuda
          actor_lr: 0.00035
          critic_lr: 0.00035
          gamma: 0.999
          lam: 0.95
          clip_eps: 0.15
          update_epochs: 5
          batch_size: 4096
          minibatch_size: 256
          max_grad_norm: 0.5
          ent_coef: 0.00
          normalize_adv: true
          gae_lambda: 0.95
          sequence_batch_size: 1
          hidden_dims:
            - 512
            - 256
            # - 128
          observation_normalization: running
          target_kl: 0.015
          # entropy_schedule:
          #   type: linear
          #   start: 0.02
          #   end: 0.005
          #   steps: 600000
          # learning_rate_schedule:
          #   type: linear
          #   start: 0.0003
          #   end: 0.00005
          #   steps: 600000
          initial_speed: 1.80
          initial_speed_warmup_steps: 180
          initial_speed_warmup_throttle: 0.5
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          include_truncation: true
      reward:
        task: gaplock
        ignore_non_trainable: true
        idle_speed_threshold: 0
        idle_patience_steps: 0
        features:
          - gaplock_offense
          - gaplock_pinch_pocket
          - gaplock_force_clearance
          - gaplock_force_turn
        params:
          target_crash_reward: 200.0
          self_collision_penalty: -220.0

          truncation_penalty: -150.0
          step_reward: -0.01
          idle_speed_threshold: 0.2
          idle_penalty_steps: 40
          idle_penalty: -0.001
          idle_truncation_penalty: -5.0

          pressure_distance: 1.6
          pressure_timeout: 1.5
          pressure_min_speed: 0.25
          pressure_bonus: 0.002
          pressure_bonus_interval: 10
          success_requires_pressure: true

          speed_bonus_coef: -0.03
          speed_bonus_target: 2.5

          distance_reward_far_distance: 4.0
          distance_penalty_far: 0.01
          lidar_filter_range_max: 12.0
          target_neighborhood_r_max: 6.0

          # LiDAR wall-proxy bounds for reward computation
          lidar_filter_range_min: 0.35
          lidar_filter_range_max: 12.0
          target_neighborhood_r_min: 0.40
          target_neighborhood_r_max: 6.0
          target_neighborhood_x_band: 2.2
          target_side_y_epsilon: 0.08

          # Pinch pocket geometry (new)
          pocket_reward_weight: 0.08
          pinch_anchor_dx: 1.3
          pinch_anchor_dy: 0.8
          pinch_sigma: 0.55
          pinch_in_front_x_min: 0.45
          pinch_pressure_distance: 1.6
          pinch_pressure_heading_tol_deg: 35
          pinch_pressure_recent_seconds: 1.5

          # Forcing via opposite-side clearance shrink (new)
          force_reward_weight: 1.5
          force_reward_time_scaled: true
          force_reward_clip: 0.15
          force_reward_band_min: 0.45
          force_reward_band_max: 3.2
          force_reward_enable_ema: true
          force_reward_ema_alpha: 0.45

          # Target yaw-rate hint (new, optional but helpful early)
          turn_reward_weight: 0.20
          turn_reward_time_scaled: true
          turn_reward_clip: 0.15
      wrappers:
        - factory: obs
          params:
            max_scan: 12.0
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 720
                  max_range: 12.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1

    car_1:
      trainable: false
      role: defender
      algorithm:
        name: follow_gap
        params:
          max_distance: 12.0
          window_size: 5
          bubble_radius: 70
          max_steer: 1.0
          min_speed: 0.1
          max_speed: 2.0
          steering_gain: 20.0
          fov_deg: 240
          # target_mode: farthest
          use_disparity_extender: true
          safety_margin: 0.08
          cutback_clearance: 0.9
          cutback_hold_steps: 8
          # gap_min_range: 0.65
          steer_smooth: 0.1
          center_bias_gain: 0.00
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
