meta:
  name: gaplock_dqn

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 10000
    lidar_beams: 54

    terminate_on_any_done: true
    random_spawn: true


  main:
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: dqn
      tags:
        - dqn
    mode: train_eval
    save_eval_rollouts: true
    eval_rollout_dir: eval_rollouts
    train_episodes: 10000
    eval_episodes: 1
    checkpoint: checkpoints/dqn_gaplock/dqn_gaplock.pt

  agents:
    car_0:
      trainable: true
      algorithm:
        name: dqn
        params:
          device: cpu
          action_repeat: 1
          lr: 0.0004
          gamma: 0.995
          batch_size: 64
          buffer_size: 150000
          target_update_interval: 200
          updates_per_step: 2
          noisy_layers: false
          epsilon_enabled: true
          epsilon_start: 0.98
          epsilon_end: 0.05
          epsilon_decay_rate: 0.996
          hidden_dims:
            - 256
            - 512
            - 128
          prioritized_replay: true
          per_alpha: 0.6
          per_beta_start: 0.35
          per_beta_increment: 2.0e-04
          per_min_priority: 0.001
          per_epsilon: 1.0e-06
          action_mode: rate
          steering_rate: 4.0
          accel_rate: 6.5
          brake_rate: 6.5
          rate_initial_speed: 2.5
          save_dir: checkpoints/dqn_gaplock
          checkpoint_name: dqngaplock.pt
      reward:
        task: gaplock
        idle_speed_threshold: 0.05
        idle_patience_steps: 120
        features:
          - gaplock_offense
          - idle_guard
        params:
          target_crash_reward: 40.0
          self_collision_penalty: -10.0
          reward_weight: null
          reward_decay: null
          reward_smoothing: null
          step_reward: 0.05
          idle_speed_threshold: 0.05
          idle_truncation_penalty: -2.0
          relative_reward:
            weights:
              front: 0.0
              front_right: 0.25
              right: 0.1
              back_right: 0.0
              back: -0.0
              back_left: 0.0
              left: 0.1
              front_left: 0.25
            preferred_radius: 0.9
            inner_tolerance: 0.1
            outer_tolerance: 0.1
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
              - id: ego_pose
                type: ego_pose
                params:
                  normalize_xy: 30.0
                  angle_mode: sin_cos
              - id: ego_velocity
                type: velocity
                params:
                  normalize: 10.0
                  include_speed: true
                  speed_scale: 10.0
              - id: ego_collision
                type: collision
              - id: relative_pose
                type: relative_pose
                params:
                  normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_collision
                type: collision
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_speed: 20.0
          min_speed: 2.5
          steering_gain: 1.0
          bubble_radius: 4.0
          steer_smooth: 0.0
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
