meta:
  name: gaplock_td3

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 5000
    lidar_beams: 720
    terminate_on_any_done: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
      s_min: -0.46
      s_max: 0.46
    spawn_points:
      - spawn_2
      - spawn_1
    spawn_cycle: true
    spawn_point_sets:
      - id: attacker_ahead_a
        names: [spawn_3, spawn_1]
      - id: attacker_ahead_b
        names: [spawn_4, spawn_1]
      - id: attacker_far_a
        names: [spawn_5, spawn_2]
      - id: attacker_far_b
        names: [spawn_6, spawn_2]

  main:
    mode: train
    train_episodes: 1500

    checkpoint: checkpoints/td3_gaplock/td3_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: gaplock_runs
      tags:
        - td3

  agents:
    car_0:
      trainable: true
      role: attacker
      algorithm:
        name: td3
        params:
          device: cuda
          actor_lr: 0.0005
          critic_lr: 0.0005
          actor_optimizer: adamw
          actor_weight_decay: 0.0001
          
          actor_lr_scheduler:
            type: cosine
            t_max: 200000
            eta_min: 0.00002

          critic_lr_scheduler:
            type: step
            step_size: 150000
            gamma: 0.5

          gamma: 0.99
          tau: 0.005
          policy_noise: 0.2
          noise_clip: 0.5
          policy_delay: 2

          batch_size: 256
          buffer_size: 1000000
          warmup_steps: 5000
          success_buffer_size: 200000
          success_buffer_ratio: 0.25

          updates_per_step: 1
          include_truncation: true
          time_limit_terminal: false

          use_per: false
          per_alpha: 0.6
          per_beta_start: 0.4
          # per_beta: 0.5
          per_beta_final: 1.0
          per_beta_increment: 0.000001
          per_min_priority: 0.00001
          per_epsilon: 0.00001
          exploration_noise: 0.15
          exploration_noise_final: 0.1
          # exploration_noise_decay_steps: 3000000
          exploration_noise_decay_episodes: 1500
          initial_speed: 1.0
          initial_speed_choices:
            - 0.2
            - 0.4
            - 0.5
            - 0.8
            - 1.0
          initial_speed_warmup_steps: 180
          initial_speed_warmup_throttle: 0.5
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          hidden_dims:
            - 512
            - 256
            - 128

          save_dir: checkpoints/td3_gaplock
          checkpoint_name: td3_gaplock.pt
      reward:
        task: gaplock
        ignore_non_trainable: true
        features:
          - gaplock_offense

        # (runner/framework-level) idle termination; keep it here, NOT inside params
        idle_speed_threshold: 0.12
        idle_patience_steps: 120

        params:
          # --- terminal outcomes ---
          target_crash_reward: 60.0
          self_collision_penalty: -90.0
          truncation_penalty: -20.0
          success_once: true
          success_requires_pressure: true

          # --- stability / anti-exploit ---
          reward_clip: 2.0
          step_reward: -0.002

          # --- idle shaping (reward-side; separate from runner termination) ---
          idle_speed_threshold: 0.12
          idle_penalty_steps: 25
          idle_penalty: 0.05
          idle_truncation_penalty: -5.0

          # --- pressure gating ---
          pressure_distance: 1.30
          pressure_timeout: 1.20
          pressure_min_speed: 0.30
          pressure_heading_tolerance: 1.57
          pressure_bonus: 0.12
          pressure_bonus_interval: 5
          pressure_streak_bonus: 0.10
          pressure_streak_cap: 40

          # --- speed / control discouragement ---
          speed_bonus_coef: 0.05
          speed_bonus_target: 0.60
          reverse_penalty: 0.10
          reverse_speed_threshold: 0.02
          brake_penalty: 0.05
          brake_speed_threshold: 0.40
          brake_drop_threshold: 0.25

          # --- distance + heading shaping ---
          heading_reward_coef: 0.08
          distance_reward_near: 0.12
          distance_reward_near_distance: 1.00
          distance_reward_far_distance: 2.50
          distance_penalty_far: 0.08
          proximity_penalty_distance: 4.50
          proximity_penalty_value: 0.05
          distance_gradient:
            scale: 0.20
            time_scaled: true
            clip: [-0.20, 0.20]
            points:
              - [0.25, -1.00]
              - [0.80,  0.70]
              - [1.20,  0.60]
              - [2.50,  0.00]
              - [4.50, -0.60]
              - [6.00, -1.00]

          # --- pinch pocket + potential field ---
          pocket_reward_weight: 0.12
          pinch_anchor_dx: 0.55
          pinch_anchor_dy: 0.45
          pinch_sigma: 0.35
          pinch_in_front_x_min: 0.25
          pinch_pressure_distance: 0.90
          pinch_pressure_heading_tol_deg: 35.0
          pinch_pressure_recent_seconds: 1.00

          potential_field_weight: 0.80
          potential_field_sigma: 0.45
          potential_field_radius: 2.00
          potential_field_peak: 0.60
          potential_field_floor: -0.25
          potential_field_power: 2.0
          potential_field_time_scaled: true

          # --- LiDAR geometry ---
          lidar_filter_range_min: 0.15
          lidar_filter_range_max: 12.0
          lidar_fov_radians: 4.1887902047863905
          lidar_range_max: 12.0
          target_neighborhood_r_min: 0.30
          target_neighborhood_r_max: 6.00
          target_neighborhood_x_band: 2.00
          target_side_y_epsilon: 0.05

          # --- forcing + turn shaping ---
          force_reward_weight: 6.0
          force_reward_enable_ema: true
          force_reward_ema_alpha: 0.40
          force_reward_band_min: 0.45
          force_reward_band_max: 3.20
          force_reward_clip: 0.25
          force_reward_time_scaled: true

          turn_reward_weight: 2.0
          turn_reward_clip: 0.35
          turn_reward_time_scaled: true

          # --- leave off unless you use them ---
          commit_distance: 0.0
          commit_heading_threshold: 0.0
          commit_speed_threshold: 0.0
          commit_bonus: 0.0
          escape_distance: 0.0
          escape_penalty: 0.0
          success_border_radius: 0.0
          success_border_lane_center: 0.0
          success_border_requires_pressure: false
          target_offsets: null
          target_offset_radius: 0.0
          target_offset_falloff: 0.0
          target_offset_marker_radius: 0.0
          target_offset_marker_segments: 16
          relative_reward: null
          reward_horizon: null
          reward_weight: null
          reward_decay: null
          reward_smoothing: null
          reward_ring_focus_agent: null


      wrappers:
        - factory: obs
          params:
            max_scan: 12.0
            # normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 720
                  max_range: 12.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1


    car_1:
      trainable: false
      role: defender
      algorithm:
        name: follow_gap
        params:
          max_distance: 12.0
          window_size: 5
          bubble_radius: 70
          max_steer: 1.0
          min_speed: 0.1
          max_speed: 1.0
          steering_gain: 20.0
          fov_deg: 240
          # target_mode: farthest
          use_disparity_extender: true
          safety_margin: 0.08
          cutback_clearance: 0.9
          cutback_hold_steps: 8
          # gap_min_range: 0.65
          steer_smooth: 0.1
          center_bias_gain: 0.00
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
      # policy_curriculum:
      #   success_window: 40
      #   activation_samples: 30
      #   cooldown: 25
      #   persist: true
      #   stages:
      #     - name: tier0_dumb_defender
      #       params:
      #         max_speed: 0.80
      #         min_speed: 0.35
      #         steering_gain: 0.25
      #         steer_smooth: 0.5
      #         crawl_steer_ratio: 0.55
      #         center_bias_gain: 0.0
      #         inside_bias_gain: 0.0
      #         preview_horizon: 0.0
      #         preview_samples: 0
      #         dwa_samples: 0
      #         enhanced_gap_scoring: false
      #         u_shape_enabled: false
      #     - name: tier1_preview_defender
      #       enable_rate: 0.3
      #       enable_patience: 3
      #       params:
      #         max_speed: 0.80
      #         min_speed: 0.3
      #         steering_gain: 0.32
      #         steer_smooth: 0.42
      #         crawl_steer_ratio: 0.45
      #         center_bias_gain: 0.05
      #         inside_bias_gain: 0.1
      #         preview_horizon: 0.8
      #         preview_samples: 5
      #         dwa_samples: 0
      #         enhanced_gap_scoring: true
      #         dwa_horizon: 0.5
      #         dwa_heading_weight: 0.2
      #         u_shape_enabled: false
      #     - name: tier2_top_defender
      #       enable_rate: 0.55
      #       enable_patience: 4
      #       params:
      #         max_distance: 8.0
      #         window_size: 2
      #         bubble_radius: 1
      #         max_steer: 0.35
      #         min_speed: 0.2
      #         max_speed: 0.80
      #         steering_gain: 0.4
      #         fov_deg: 240
      #         # normalized: true
      #         steer_smooth: 0.35
      #         center_bias_gain: 0.09
      #         inside_bias_gain: 0.2
      #         crawl_steer_ratio: 0.35
      #         steering_speed_scale: 1.0
      #         preview_horizon: 1.5
      #         preview_samples: 7
      #         dwa_samples: 5
      #         dwa_horizon: 0.5
      #         dwa_heading_weight: 0.15
      #         enhanced_gap_scoring: true
      #         gap_score_width_weight: 1.0
      #         gap_score_clearance_weight: 1.2
      #         gap_score_center_weight: 0.5
      #         gap_score_curvature_weight: 0.2
      #         u_shape_enabled: false
