meta:
  name: gaplock_td3

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 25000
    lidar_beams: 720
    lidar_dist: 0.103
    terminate_on_any_done: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
      s_min: -0.46
      s_max: 0.46
    spawn_points:
      - spawn_1
      - spawn_2
    spawn_point_sets:
      - id: offset_lane_a
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_3
          - spawn_1
      - id: offset_lane_b
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_2
          - spawn_1
      - id: extended_gap
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_4
          - spawn_1
    spawn_curriculum:
      min_episode: 150
      activation_samples: 40
      success_window: 8
      enable_rate: 0.7
      enable_patience: 4
      disable_rate: 0.3
      disable_patience: 2
      cooldown: 20
      persist: true

  main:
    mode: train
    train_episodes: 800
    eval_episodes: 0
    eval_interval: 0
    federated:
      enabled: false
      interval: 50
      agents:
        - car_0
      root: outputs/federated_gaplock
      mode: mean
      timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/td3_gaplock/td3_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: gaplock_runs
      tags:
        - td3

  agents:
    car_0:
      trainable: true
      role: attacker
      algorithm:
        name: td3
        params:
          device: cuda
          actor_lr: 0.004
          critic_lr: 0.005
          actor_optimizer: adamw
          actor_weight_decay: 0.0001
          actor_lr_scheduler:
            type: cosine
            t_max: 200000
            eta_min: 0.00002
          critic_lr_scheduler:
            type: step
            step_size: 150000
            gamma: 0.5
          gamma: 0.99
          tau: 0.01
          policy_noise: 0.2
          noise_clip: 0.5
          policy_delay: 2
          batch_size: 256
          buffer_size: 100000
          warmup_steps: 5000
          updates_per_step: 2
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.4
          # per_beta: 0.5
          per_beta_final: 1.0
          per_beta_increment: 0.00075
          per_min_priority: 0.00001
          per_epsilon: 0.00001
          exploration_noise: 0.2
          exploration_noise_final: 0.05
          # exploration_noise_decay_steps: 3000000
          exploration_noise_decay_episodes: 600
          initial_speed: 0.9
          initial_speed_warmup_steps: 150
          initial_speed_warmup_throttle: 0.8
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          hidden_dims:
            - 512
            - 256
            - 128
          save_dir: checkpoints/td3_gaplock
          checkpoint_name: td3_gaplock.pt
      reward:
        task: gaplock
        ignore_non_trainable: true
        idle_speed_threshold: 0
        idle_patience_steps: 0
        features:
          - gaplock_offense
          - gaplock_pinch_pocket
          - gaplock_force_clearance
          - gaplock_force_turn

        params:
          target_crash_reward: 100.0
          self_collision_penalty: -50.0
          truncation_penalty: -50.0
          # reward_weight: null
          # reward_decay: null
          # reward_smoothing: null
          step_reward: -0.0000
          idle_speed_threshold: 0.0
          idle_penalty: 0.0
          idle_penalty_steps: 0
          idle_truncation_penalty: 0.0
          pressure_distance: 1.0
          pressure_timeout: 0.5
          pressure_min_speed: 0.25
          pressure_bonus: 0.015
          pressure_bonus_interval: 4
          # # proximity_penalty_distance: 0.0
          # # proximity_penalty_value: 0.0
          # speed_bonus_coef: 0.05
          # speed_bonus_target: 0.6
          # reverse_penalty: 15.0
          # reverse_speed_threshold: 0.01
          # brake_penalty: 0.2
          # brake_speed_threshold: 0.05
          # brake_drop_threshold: 0.2
          # heading_reward_coef: 0.08
          distance_reward_near: 0.025
          distance_reward_near_distance: 0.8
          distance_reward_far_distance: 2.0
          distance_penalty_far: 0.01
          pressure_streak_bonus: 0.01
          pressure_streak_cap: 0
          # commit_distance: 0.4
          # commit_heading_threshold: 0.2
          # commit_speed_threshold: 0.3
          # commit_bonus: 0.5
          # escape_distance: 0.0
          # escape_penalty: 0.0
          # success_border_radius: 0.5
          # success_border_lane_center: -0.724998
          distance_gradient:
            points:
              - distance: 0.4
                value: 0.1
              - distance: 2.0
                value: 0.02
              - distance: 5.0
                value: -0.1
            scale: 1.0
            time_scaled: true
            clip:
              - -0.1
              - 0.1

          target_offsets:
            - forward: 0.55
              left: 0.22
            - forward: 0.55
              left: -0.22
          target_offset_radius: 0.15
          target_offset_falloff: 0.05
          target_offset_marker_radius: 0.15
    
          relative_reward:
            weights:
              front: 0.25
              front_right: 0.35
              right: 0.15
              back_right: 0.05
              back: 0.01
              back_left: 0.05
              left: 0.15
              front_left: 0.35
            preferred_radius: 0.3
            inner_tolerance: 0.0
            outer_tolerance: 0.5
            # ignored_agents:
            #   - car_1
          lidar_filter_range_max: 8.0
          target_neighborhood_r_max: 6.0
      wrappers:
        - factory: obs
          params:
            max_scan: 8.0
            # normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 720
                  max_range: 8.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1


    car_1:
      trainable: false
      role: defender
      algorithm:
        name: follow_gap
        params:
          max_distance: 8.0
          window_size: 2
          bubble_radius: 1
          max_steer: 0.35
          min_speed: 0.2
          max_speed: 0.80
          steering_gain: 0.4
          fov_deg: 240
          # normalized: true
          steer_smooth: 0.35
          center_bias_gain: 0.09
          inside_bias_gain: 0.2
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
      # policy_curriculum:
      #   success_window: 40
      #   activation_samples: 30
      #   cooldown: 25
      #   persist: true
      #   stages:
      #     - name: tier0_dumb_defender
      #       params:
      #         max_speed: 0.80
      #         min_speed: 0.35
      #         steering_gain: 0.25
      #         steer_smooth: 0.5
      #         crawl_steer_ratio: 0.55
      #         center_bias_gain: 0.0
      #         inside_bias_gain: 0.0
      #         preview_horizon: 0.0
      #         preview_samples: 0
      #         dwa_samples: 0
      #         enhanced_gap_scoring: false
      #         u_shape_enabled: false
      #     - name: tier1_preview_defender
      #       enable_rate: 0.3
      #       enable_patience: 3
      #       params:
      #         max_speed: 0.80
      #         min_speed: 0.3
      #         steering_gain: 0.32
      #         steer_smooth: 0.42
      #         crawl_steer_ratio: 0.45
      #         center_bias_gain: 0.05
      #         inside_bias_gain: 0.1
      #         preview_horizon: 0.8
      #         preview_samples: 5
      #         dwa_samples: 0
      #         enhanced_gap_scoring: true
      #         dwa_horizon: 0.5
      #         dwa_heading_weight: 0.2
      #         u_shape_enabled: false
      #     - name: tier2_top_defender
      #       enable_rate: 0.55
      #       enable_patience: 4
      #       params:
      #         max_distance: 8.0
      #         window_size: 2
      #         bubble_radius: 1
      #         max_steer: 0.35
      #         min_speed: 0.2
      #         max_speed: 0.80
      #         steering_gain: 0.4
      #         fov_deg: 240
      #         # normalized: true
      #         steer_smooth: 0.35
      #         center_bias_gain: 0.09
      #         inside_bias_gain: 0.2
      #         crawl_steer_ratio: 0.35
      #         steering_speed_scale: 1.0
      #         preview_horizon: 1.5
      #         preview_samples: 7
      #         dwa_samples: 5
      #         dwa_horizon: 0.5
      #         dwa_heading_weight: 0.15
      #         enhanced_gap_scoring: true
      #         gap_score_width_weight: 1.0
      #         gap_score_clearance_weight: 1.2
      #         gap_score_center_weight: 0.5
      #         gap_score_curvature_weight: 0.2
      #         u_shape_enabled: false
