meta:
  name: gaplock_sac_eval_eager_sweep_5
scenario:
  env:
    lidar_beams: 108
    map: line2
    max_steps: 1500
    seed: 42
    spawn_curriculum:
      activation_samples: 40
      cooldown: 20
      disable_patience: 2
      disable_rate: 0.3
      enable_patience: 4
      enable_rate: 0.7
      min_episode: 0
      persist: true
      start_enabled: true
      success_window: 8
    spawn_point_sets:
    - id: offset_lane_a
      metadata:
        spawn_option_id: spawn_random
      names:
      - spawn_3
      - spawn_1
    - id: offset_lane_b
      metadata:
        spawn_option_id: spawn_random
      names:
      - spawn_2
      - spawn_1
    - id: extended_gap
      metadata:
        spawn_option_id: spawn_random
      names:
      - spawn_4
      - spawn_1
    spawn_points:
    - spawn_2
    - spawn_1
    terminate_on_any_done: true
    vehicle_params:
      length: 0.32
      v_max: 1.0
      v_min: -1.0
      width: 0.225
      s_min: -0.46
      s_max: 0.46
  main:
    checkpoint: plots/eager-sweep-3/20251112-132218/sac_best_eager-sweep-5.pt
    eval_episodes: 25
    eval_interval: 0
    eval_rollout_dir: eval_rollouts
    mode: eval
    save_eval_rollouts: false
    train_episodes: 0
    wandb:
      enabled: false
      entity: ahoop004-old-dominion-university
      group: gaplock_sac
      project: marl-f110
      tags:
      - sac
    output_root: .
  agents:
    car_0:
      trainable: true
      algorithm:
        name: sac
        params:
          actor_lr: 0.03811428414947935
          alpha_lr: 0.03180716614848562
          auto_alpha: true
          batch_size: 512
          buffer_size: 200000
          critic_lr: 0.05080882954947798
          device: cpu
          exploration_noise: 0.2
          exploration_noise_decay_steps: 300000
          exploration_noise_final: 0.05
          gamma: 0.99
          hidden_dims:
          - 512
          - 256
          - 128
          include_truncation: true
          initial_speed: 0.9
          initial_speed_warmup_steps: 120
          initial_speed_warmup_throttle: 0.4
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          target_entropy: -2.5
          tau: 0.005
          warmup_steps: 5000
      reward:
        task: gaplock
        ignore_non_trainable: true
        idle_speed_threshold: 0.2
        idle_patience_steps: 40
        features:
          - gaplock_offense
        params:
          target_crash_reward: 200.0
          self_collision_penalty: -220.0

          truncation_penalty: -150.0
          step_reward: -0.001
          idle_speed_threshold: 0.02
          idle_penalty_steps: 140
          idle_penalty: -0.001
          idle_truncation_penalty: -5.0

          pressure_distance: 0.0
          pressure_timeout: 0.0
          pressure_min_speed: 0.0
          pressure_bonus: 0.0
          pressure_bonus_interval: 1
          success_requires_pressure: false

          speed_bonus_coef: 0.0
          speed_bonus_target: 0.0

          distance_reward_far_distance: 0.0
          distance_penalty_far: 0.0

          # LiDAR wall-proxy bounds for reward computation
          lidar_filter_range_min: 0.35
          lidar_filter_range_max: 12.0
          target_neighborhood_r_min: 0.40
          target_neighborhood_r_max: 6.0
          target_neighborhood_x_band: 2.2
          target_side_y_epsilon: 0.08

          # Pinch pocket geometry (new)
          pocket_reward_weight: 0.0
          pinch_anchor_dx: 0.3
          pinch_anchor_dy: 0.45
          pinch_sigma: 0.35
          pinch_in_front_x_min: 0.45
          pinch_pressure_distance: 1.6
          pinch_pressure_heading_tol_deg: 35
          pinch_pressure_recent_seconds: 1.5

          # Potential-field reward (Gaussian, centered on pinch anchors)
          # Set `potential_field_weight` > 0 to enable.
          potential_field_weight: 2.0
          potential_field_sigma: 0.6
          potential_field_peak: 1.0
          potential_field_floor: -0.2
          potential_field_power: 1.5
          potential_field_time_scaled: true

          # Forcing via opposite-side clearance shrink (new)
          force_reward_weight: 10.0
          force_reward_time_scaled: false
          force_reward_clip: 0.15
          force_reward_band_min: 0.45
          force_reward_band_max: 3.2
          force_reward_enable_ema: true
          force_reward_ema_alpha: 0.45

          # Target yaw-rate hint (new, optional but helpful early)
          turn_reward_weight: 3.0
          turn_reward_time_scaled: false
          turn_reward_clip: 0.15
      trainable: true
      wrappers:
      - factory: obs
        params:
          components:
          - id: lidar
            params:
              beams: 108
              clip: 1.0
              max_range: 30.0
              normalize: true
            type: lidar
          - id: ego_pose
            params:
              angle_mode: sin_cos
              normalize_xy: 51.224998
            type: ego_pose
          - id: ego_vel
            params:
              include_speed: true
              normalize: 2.0
              speed_scale: 1.0
            type: velocity
          - id: target_pose
            params:
              angle_mode: sin_cos
              normalize_xy: 51.224998
            target:
              agent: car_1
            type: target_pose
          - id: target_vel
            params:
              include_speed: true
              normalize: 2.0
              speed_scale: 1.0
            target:
              agent: car_1
            type: velocity
          - id: relative_pose
            params:
              angle_mode: sin_cos
              normalize_xy: 51.224998
            target:
              agent: car_1
            type: relative_pose
          max_scan: 30.0
    car_1:
      algorithm:
        name: follow_gap
        params:
          bubble_radius: 1
          center_bias_gain: 0.09
          crawl_steer_ratio: 0.35
          dwa_heading_weight: 0.15
          dwa_horizon: 0.5
          dwa_samples: 5
          enhanced_gap_scoring: true
          fov_deg: 270
          gap_score_center_weight: 0.5
          gap_score_clearance_weight: 1.2
          gap_score_curvature_weight: 0.2
          gap_score_width_weight: 1.0
          inside_bias_gain: 0.2
          max_distance: 30.0
          max_speed: 1.0
          max_steer: 0.35
          min_speed: 0.2
          normalized: true
          preview_horizon: 1.5
          preview_samples: 7
          steer_smooth: 0.35
          steering_gain: 0.4
          steering_speed_scale: 1.0
          u_shape_enabled: false
          window_size: 2
      policy_curriculum:
        activation_samples: 30
        cooldown: 25
        persist: true
        stages:
        - name: tier0_dumb_defender
          params:
            center_bias_gain: 0.0
            crawl_steer_ratio: 0.55
            dwa_samples: 0
            enhanced_gap_scoring: false
            inside_bias_gain: 0.0
            max_speed: 1.0
            min_speed: 0.35
            preview_horizon: 0.0
            preview_samples: 0
            steer_smooth: 0.5
            steering_gain: 0.25
            u_shape_enabled: false
        - enable_patience: 3
          enable_rate: 0.3
          name: tier1_preview_defender
          params:
            center_bias_gain: 0.05
            crawl_steer_ratio: 0.45
            dwa_heading_weight: 0.2
            dwa_horizon: 0.5
            dwa_samples: 0
            enhanced_gap_scoring: true
            inside_bias_gain: 0.1
            max_speed: 1.0
            min_speed: 0.3
            preview_horizon: 0.8
            preview_samples: 5
            steer_smooth: 0.42
            steering_gain: 0.32
            u_shape_enabled: false
        - enable_patience: 4
          enable_rate: 0.55
          name: tier2_top_defender
          params:
            bubble_radius: 1
            center_bias_gain: 0.09
            crawl_steer_ratio: 0.35
            dwa_heading_weight: 0.15
            dwa_horizon: 0.5
            dwa_samples: 5
            enhanced_gap_scoring: true
            fov_deg: 270
            gap_score_center_weight: 0.5
            gap_score_clearance_weight: 1.2
            gap_score_curvature_weight: 0.2
            gap_score_width_weight: 1.0
            inside_bias_gain: 0.2
            max_distance: 30.0
            max_speed: 1.0
            max_steer: 0.35
            min_speed: 0.2
            normalized: true
            preview_horizon: 1.5
            preview_samples: 7
            steer_smooth: 0.35
            steering_gain: 0.4
            steering_speed_scale: 1.0
            u_shape_enabled: false
            window_size: 2
        success_window: 40
      trainable: false
