meta:
  name: gaplock_td3

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 1500
    lidar_beams: 54
    terminate_on_any_done: true
    spawn_point_sets:
      - id: baseline_pair
        names:
          - spawn_1
          - spawn_2
    spawn_point_randomize:
      pool:
        - spawn_1
        - spawn_2
        - spawn_3
        - spawn_4
        - spawn_5
        - spawn_6
        - spawn_7
        - spawn_8
      allow_reuse: false
    spawn_curriculum:
      min_episode: 1000
      success_window: 200
      enable_rate: 0.7
      enable_patience: 3
      disable_rate: 0.5
      disable_patience: 2
      cooldown: 200

  main:
    mode: train_eval
    train_episodes: 15000
    eval_episodes: 5
    eval_interval: 10
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/td3_gaplock_v2/td3_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: td3
      tags:
        - td3

  agents:
    car_0:
      trainable: true
      algorithm:
        name: td3
        params:
          device: cpu
          actor_lr: 0.00025
          critic_lr: 0.0005
          gamma: 0.995
          tau: 0.005
          policy_noise: 0.2
          noise_clip: 0.4
          policy_delay: 2
          batch_size: 256
          buffer_size: 262144
          warmup_steps: 8000
          updates_per_step: 2
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.5
          per_beta: 0.5
          per_beta_increment: 0.000005
          per_min_priority: 0.0001
          per_epsilon: 0.000001
          exploration_noise: 0.3
          exploration_noise_final: 0.05
          exploration_noise_decay_steps: 200000
          exploration_noise_decay_episodes: 0
          initial_speed: 2.8
          prevent_reverse: true
          prevent_reverse_min_speed: 0.1
          prevent_reverse_speed_index: 1
          hidden_dims:
            - 256
            - 256
            - 128
          save_dir: checkpoints/td3_gaplock_v2
          checkpoint_name: td3_gaplock.pt
      reward:
        task: gaplock
        idle_speed_threshold: 0.2
        idle_patience_steps: 90
        features:
          - gaplock_offense
          - idle_guard
        params:
          target_crash_reward: 80.0
          self_collision_penalty: -10.0
          reward_weight: null
          reward_decay: null
          reward_smoothing: null
          step_reward: 0.05
          idle_speed_threshold: 0.25
          idle_penalty: -0.03
          idle_penalty_steps: 12
          idle_truncation_penalty: -25.0
          pressure_distance: 1.1
          pressure_timeout: 0.8
          pressure_min_speed: 0.15
          pressure_bonus: 3.0
          pressure_bonus_interval: 4
          proximity_penalty_distance: 2.0
          proximity_penalty_value: -0.02
          relative_reward:
            weights:
              front: 0.05
              front_right: 0.04
              right: 0.02
              back_right: -0.01
              back: -0.02
              back_left: -0.01
              left: 0.02
              front_left: 0.04
            preferred_radius: 0.7
            inner_tolerance: 0.1
            outer_tolerance: 0.2
            ignored_agents:
              - car_1
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_velocity
                type: velocity
                params:
                  normalize: 10.0
                  include_speed: true
                  speed_scale: 10.0
              - id: ego_collision
                type: collision
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: relative_sector
                type: relative_sector
                params:
                  preferred_radius: 0.7
                  inner_tolerance: 0.1
                  outer_tolerance: 0.2
                target:
                  agent: car_1
              - id: target_collision
                type: collision
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_speed: 10.0
          min_speed: 2.5
          steering_gain: 1.0
          bubble_radius: 2.0
          steer_smooth: 0.0
      defender_curriculum:
        min_episode: 3000
        success_window: 200
        activation_samples: 200
        enable_patience: 4
        disable_patience: 2
        cooldown: 300
        persist: false
        stages:
          - name: baseline
            params:
              max_speed: 8.0
              min_speed: 2.0
              steering_gain: 1.0
              bubble_radius: 2.0
              steer_smooth: 0.0
          - name: pressure
            enable_rate: 0.6
            disable_rate: 0.5
            params:
              max_speed: 11.0
              steering_gain: 1.1
              bubble_radius: 2.5
              steer_smooth: 0.1
          - name: aggressive
            enable_rate: 0.75
            disable_rate: 0.6
            params:
              max_speed: 12.5
              steering_gain: 1.25
              bubble_radius: 3.0
              steer_smooth: 0.15
          - name: lockdown
            enable_rate: 0.85
            disable_rate: 0.7
            params:
              max_speed: 13.5
              steering_gain: 1.35
              bubble_radius: 3.5
              steer_smooth: 0.2
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
