meta:
  name: gaplock_sac

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 35000
    lidar_beams: 720
    terminate_on_any_done: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
    spawn_points:
      - spawn_2
      - spawn_1
    # spawn_point_sets:
    #   - id: offset_lane_a
    #     metadata:
    #       spawn_option_id: spawn_random
    #     names:
    #       - spawn_3
    #       - spawn_1
    #   - id: offset_lane_b
    #     metadata:
    #       spawn_option_id: spawn_random
    #     names:
    #       - spawn_2
    #       - spawn_1
    #   - id: extended_gap
    #     metadata:
    #       spawn_option_id: spawn_random
    #     names:
    #       - spawn_4
    #       - spawn_1
    # spawn_curriculum:
    #   min_episode: 120
    #   activation_samples: 40
    #   success_window: 8
    #   enable_rate: 0.7
    #   enable_patience: 4
    #   disable_rate: 0.3
    #   disable_patience: 2
    #   cooldown: 20
    #   persist: true
    #   start_enabled: true

  main:
    mode: train
    train_episodes: 1500
    eval_episodes: 10
    eval_interval: 150
    federated:
      enabled: false
      interval: 50
      agents:
        - car_0
      root: outputs/federated_gaplock
      mode: mean
      timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/sac_gaplock/sac_gaplock.pt
    # warm_start_checkpoint: outputs/checkpoints/sac_best_gaplock_sac-r01-f357d6f9.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: gaplock_sac
      tags:
        - sac

  agents:
    car_0:
      trainable: true
      algorithm:
        name: sac
        params:
          device: cuda
          actor_lr: 0.003
          critic_lr: 0.0045
          alpha_lr: 0.003
          gamma: 0.99
          tau: 0.005
          batch_size: 256
          buffer_size: 250000
          warmup_steps: 15000
          auto_alpha: true
          target_entropy: -2.2
          hidden_dims:
            - 512
            - 256
            - 128
          exploration_noise: 0.2
          exploration_noise_final: 0.05
          exploration_noise_decay_steps: 450000
          initial_speed: 0.9
          initial_speed_warmup_steps: 180
          initial_speed_warmup_throttle: 0.5
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.4
          per_beta_final: 1.0
          per_beta_increment: 1e-6
          per_min_priority: 1e-3
          per_epsilon: 1e-6
      reward:
        task: gaplock
        idle_speed_threshold: 0
        idle_patience_steps: 0
        features:
          - gaplock_offense
        params:
          target_crash_reward: 120.0
          self_collision_penalty: -10.0
          truncation_penalty: -10.0
          step_reward: -0.001
          idle_speed_threshold: 0.2
          idle_penalty_steps: 30
          idle_penalty: -0.002
          idle_truncation_penalty: -2.0
          pressure_distance: 0.85
          pressure_timeout: 0.45
          pressure_min_speed: 0.25
          pressure_bonus: 0.0
          distance_reward_far_distance: 3.0
          distance_penalty_far: 0.02
          success_requires_pressure: true
      wrappers:
        - factory: obs
          params:
            max_scan: 12.0
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 720
                  max_range: 12.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_distance: 12.0
          window_size: 5
          bubble_radius: 70
          max_steer: 1.0
          min_speed: 0.1
          max_speed: 0.6
          steering_gain: 20.0
          fov_deg: 240
          # target_mode: farthest
          use_disparity_extender: true
          safety_margin: 0.08
          cutback_clearance: 0.9
          cutback_hold_steps: 8
          # gap_min_range: 0.65
          steer_smooth: 0.1
          center_bias_gain: 0.00
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
