meta:
  name: gaplock_td3

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 2500
    lidar_beams: 108
    terminate_on_any_done: true
    # centerline_autoload: true
    # centerline_render: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
    spawn_points:
      - spawn_3
      - spawn_1
    # spawn_point_sets:
    #   - id: offset_lane_a
    #     metadata:
    #       spawn_option_id: spawn_random
    #     names:
    #       - spawn_5
    #       - spawn_1
    #   - id: offset_lane_b
    #     metadata:
    #       spawn_option_id: spawn_random
    #     names:
    #       - spawn_2
    #       - spawn_1
    #   - id: extended_gap
    #     metadata:
    #       spawn_option_id: spawn_random
    #     names:
    #       - spawn_4
    #       - spawn_1
    # spawn_curriculum:
    #   min_episode: 0
    #   activation_samples: 0
    #   success_window: 0
    #   enable_rate: 0.0
    #   enable_patience: 0
    #   disable_rate: 0.0
    #   disable_patience: 0
    #   cooldown: 0
    #   persist: true

  main:
    mode: train_eval
    train_episodes: 2000
    eval_episodes: 10
    eval_interval: 100
    federated:
      enabled: false
      interval: 50
      agents:
        - car_0
      root: outputs/federated_gaplock
      mode: mean
      timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/td3_gaplock/td3_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: gaplock_runs
      tags:
        - td3

  agents:
    car_0:
      trainable: true
      algorithm:
        name: td3
        params:
          device: cpu
          actor_lr: 0.00035
          critic_lr: 0.00045
          gamma: 0.995
          tau: 0.005
          policy_noise: 0.08
          noise_clip: 0.16
          policy_delay: 2
          batch_size: 64
          buffer_size: 50000
          warmup_steps: 512
          updates_per_step: 1
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.5
          per_beta: 0.5
          per_beta_increment: 0.000005
          per_min_priority: 0.0001
          per_epsilon: 0.000001
          exploration_noise: 0.09
          exploration_noise_final: 0.01
          exploration_noise_decay_steps: 400000
          # exploration_noise_decay_episodes: 4000
          initial_speed: 1.0
          # prevent_reverse: true
          # prevent_reverse_min_speed: 0.01
          # prevent_reverse_speed_index: 1
          hidden_dims:
            - 256
            # - 256
            - 128
          save_dir: checkpoints/td3_gaplock
          checkpoint_name: td3_gaplock.pt
      reward:
        task: gaplock
        idle_speed_threshold: 0.02
        idle_patience_steps: 180
        features:
          - gaplock_offense
          - idle_guard
        params:
          target_crash_reward: 100.0
          self_collision_penalty: -10.0
          # reward_weight: null
          # reward_decay: null
          # reward_smoothing: null
          step_reward: 0.01
          idle_speed_threshold: 0.02
          idle_penalty: -0.08
          idle_penalty_steps: 18
          idle_truncation_penalty: -35.0
          pressure_distance: 1.5
          # pressure_timeout: 0.0
          # pressure_min_speed: 0.0
          pressure_bonus: 0.05
          pressure_bonus_interval: 5
          # proximity_penalty_distance: 0.0
          # proximity_penalty_value: 0.0
          # speed_bonus_coef: 0.0
          # speed_bonus_target: 0.0
          reverse_penalty: 5.0
          reverse_speed_threshold: 0.05
          # brake_penalty: 0.0
          # brake_speed_threshold: 0.0
          # brake_drop_threshold: 0.0
          heading_reward_coef: 0.05
          distance_reward_near: 0.2
          distance_reward_near_distance: 1.5
          distance_reward_far_distance: 3.0
          distance_penalty_far: 0.05
          # pressure_streak_bonus: 0.0
          # pressure_streak_cap: 0
          # commit_distance: 0.0
          # commit_heading_threshold: 0.0
          # commit_speed_threshold: 0.0
          # commit_bonus: 0.0
          # escape_distance: 0.0
          # escape_penalty: 0.0
          # success_border_radius: 0.5
          # success_border_lane_center: -0.724998
          truncation_penalty: -25.0
          relative_reward:
            weights:
              front: 0.1
              front_right: 0.1
              right: 0.01
              back_right: 0.0
              back: 0.0
              back_left: 0.0
              left: 0.01
              front_left: 0.01
            preferred_radius: 1.0
            inner_tolerance: 0.5
            outer_tolerance: 0.5
            # ignored_agents:
            #   - car_1
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 108
                  max_range: 30.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
              - id: target_pose
                type: target_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  # normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1


    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_distance: 30.0
          window_size: 4
          bubble_radius: 2
          max_steer: 0.3
          min_speed: 0.2
          max_speed: 0.75
          steering_gain: 0.4
          fov_deg: 270
          normalized: true
          steer_smooth: 0.35
          center_bias_gain: 0.2
        
         
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 108
                  max_range: 30.0
                  normalize: true
                  clip: 1.0
              
