meta:
  name: gaplock_rainbow_dqn

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 1500
    lidar_beams: 108
    terminate_on_any_done: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
    spawn_points:
      - spawn_2
      - spawn_1
    spawn_point_sets:
      - id: offset_lane_a
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_3
          - spawn_1
      - id: offset_lane_b
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_2
          - spawn_1
      - id: extended_gap
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_4
          - spawn_1
    spawn_curriculum:
      min_episode: 150
      activation_samples: 40
      success_window: 8
      enable_rate: 0.7
      enable_patience: 4
      disable_rate: 0.3
      disable_patience: 2
      cooldown: 20
      persist: true

  main:
    mode: train
    train_episodes: 1500
    eval_episodes: 0
    eval_interval: 0
    federated:
      enabled: false
      interval: 50
      agents:
        - car_0
      root: outputs/federated_gaplock
      mode: mean
      timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/rainbow_gaplock/rainbow_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: gaplock_rainbow_dqn
      tags:
        - rainbow_dqn

  agents:
    car_0:
      trainable: true
      algorithm:
        name: r_dqn
        params:
          device: cpu
          lr: 0.0005
          gamma: 0.99
          batch_size: 128
          buffer_size: 200000
          target_update_interval: 750
          prioritized_replay: true
          per_alpha: 0.6
          per_beta_start: 0.4
          per_beta_final: 1.0
          per_beta_increment: 0.00005
          per_min_priority: 0.0001
          per_epsilon: 0.0001
          epsilon_start: 1.0
          epsilon_end: 0.05
          epsilon_decay: 300000
          noisy_std: 0.4
          hidden_dims:
            - 512
            - 512
          n_atoms: 51
          v_min: -50.0
          v_max: 50.0
          action_mode: absolute
          action_repeat: 2
          action_set:
            - [-0.35, 0.90]
            - [-0.15, 0.80]
            - [0.00, 0.80]
            - [0.15, 0.80]
            - [0.35, 0.90]
            - [-0.20, 0.30]
            - [0.00, 0.30]
            - [0.20, 0.30]
            - [0.00, 0.00]
            - [0.00, -0.50]
          prevent_reverse: true
          prevent_reverse_min_speed: 0.0
          prevent_reverse_speed_index: 1
          include_truncation: true
      reward:
        task: gaplock
        idle_speed_threshold: 0
        idle_patience_steps: 0
        features:
          - gaplock_offense
        params:
          target_crash_reward: 100.0
          self_collision_penalty: -1.0
          truncation_penalty: -5.0
          step_reward: -0.0000
          idle_speed_threshold: 0.0
          idle_penalty: 0.0
          idle_penalty_steps: 0
          idle_truncation_penalty: 0.0
          pressure_distance: 1.0
          pressure_timeout: 0.5
          pressure_min_speed: 0.25
          pressure_bonus: 0.015
          pressure_bonus_interval: 4
          distance_reward_near: 0.025
          distance_reward_near_distance: 0.8
          distance_reward_far_distance: 2.0
          distance_penalty_far: 0.01
          pressure_streak_bonus: 0.01
          pressure_streak_cap: 0
          distance_gradient:
            points:
              - distance: 0.4
                value: 0.1
              - distance: 5.0
                value: 0.5
              - distance: 10.0
                value: -0.00
            scale: 1.0
            time_scaled: true
            clip:
              - -0.1
              - 0.1
          relative_reward:
            weights:
              front: 0.25
              front_right: 0.35
              right: 0.15
              back_right: 0.05
              back: 0.01
              back_left: 0.05
              left: 0.15
              front_left: 0.35
            preferred_radius: 0.3
            inner_tolerance: 0.0
            outer_tolerance: 0.5
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 108
                  max_range: 30.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_distance: 30.0
          window_size: 2
          bubble_radius: 1
          max_steer: 0.35
          min_speed: 0.2
          max_speed: 1.0
          steering_gain: 0.4
          fov_deg: 270
          normalized: true
          steer_smooth: 0.35
          center_bias_gain: 0.09
          inside_bias_gain: 0.2
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
      policy_curriculum:
        success_window: 40
        activation_samples: 30
        cooldown: 25
        persist: true
        stages:
          - name: tier0_dumb_defender
            params:
              max_speed: 1.0
              min_speed: 0.35
              steering_gain: 0.25
              steer_smooth: 0.5
              crawl_steer_ratio: 0.55
              center_bias_gain: 0.0
              inside_bias_gain: 0.0
              preview_horizon: 0.0
              preview_samples: 0
              dwa_samples: 0
              enhanced_gap_scoring: false
              u_shape_enabled: false
          - name: tier1_preview_defender
            enable_rate: 0.3
            enable_patience: 3
            params:
              max_speed: 1.0
              min_speed: 0.3
              steering_gain: 0.32
              steer_smooth: 0.42
              crawl_steer_ratio: 0.45
              center_bias_gain: 0.05
              inside_bias_gain: 0.1
              preview_horizon: 0.8
              preview_samples: 5
              dwa_samples: 0
              enhanced_gap_scoring: true
              dwa_horizon: 0.5
              dwa_heading_weight: 0.2
              u_shape_enabled: false
          - name: tier2_top_defender
            enable_rate: 0.55
            enable_patience: 4
            params:
              max_distance: 30.0
              window_size: 2
              bubble_radius: 1
              max_steer: 0.35
              min_speed: 0.2
              max_speed: 1.0
              steering_gain: 0.4
              fov_deg: 270
              normalized: true
              steer_smooth: 0.35
              center_bias_gain: 0.09
              inside_bias_gain: 0.2
              crawl_steer_ratio: 0.35
              steering_speed_scale: 1.0
              preview_horizon: 1.5
              preview_samples: 7
              dwa_samples: 5
              dwa_horizon: 0.5
              dwa_heading_weight: 0.15
              enhanced_gap_scoring: true
              gap_score_width_weight: 1.0
              gap_score_clearance_weight: 1.2
              gap_score_center_weight: 0.5
              gap_score_curvature_weight: 0.2
              u_shape_enabled: false
