meta:
  name: gaplock_td3

scenario:
  env:
    map: line2
    seed: 42
    max_steps: 5000
    lidar_beams: 54
    terminate_on_any_done: true
    random_spawn: true

  main:
    mode: train_eval
    train_episodes: 5000
    eval_episodes: 5
    eval_interval: 10
    save_eval_rollouts: true
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/td3_gaplock/td3_gaplock.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: td3
      tags:
        - td3

  agents:
    car_0:
      trainable: true
      algorithm:
        name: td3
        params:
          device: cuda
          actor_lr: 0.0004
          critic_lr: 0.0005
          gamma: 0.995
          tau: 0.005
          policy_noise: 0.2
          noise_clip: 0.5
          policy_delay: 2
          batch_size: 256
          buffer_size: 200000
          warmup_steps: 5000
          exploration_noise: 0.5
          exploration_noise_final: 0.05
          # exploration_noise_decay_steps: 50000
          exploration_noise_decay_episodes: 4000
          prevent_reverse: true
          hidden_dims:
            - 256
            - 256
          save_dir: checkpoints/td3_gaplock
          checkpoint_name: td3_gaplock.pt
      reward:
        task: gaplock
        idle_speed_threshold: 0.05
        idle_patience_steps: 120
        features:
          - gaplock_offense
          - idle_guard
        params:
          target_crash_reward: 40.0
          self_collision_penalty: -10.0
          reward_weight: null
          reward_decay: null
          reward_smoothing: null
          step_reward: 0.001
          idle_speed_threshold: 0.2
          idle_penalty_steps: 120
          idle_truncation_penalty: -10.0
          relative_reward:
            weights:
              front: 0.0
              front_right: 0.0025
              right: 0.001
              back_right: 0.0
              back: -0.0
              back_left: 0.0
              left: 0.001
              front_left: 0.0025
            preferred_radius: 0.8
            inner_tolerance: 0.2
            outer_tolerance: 0.1
            ignored_agents:
              - car_1
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
              - id: ego_pose
                type: ego_pose
                params:
                  normalize_xy: 30.0
                  angle_mode: sin_cos
              - id: ego_velocity
                type: velocity
                params:
                  normalize: 10.0
                  include_speed: true
                  speed_scale: 10.0
              - id: ego_collision
                type: collision
              - id: relative_pose
                type: relative_pose
                params:
                  normalize_xy: 30.0
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: relative_sector
                type: relative_sector
                params:
                  preferred_radius: 0.8
                  inner_tolerance: 0.2
                  outer_tolerance: 0.1
                target:
                  agent: car_1
              - id: target_collision
                type: collision
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_speed: 20.0
          min_speed: 2.5
          steering_gain: 1.0
          bubble_radius: 4.0
          steer_smooth: 0.0
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 54
                  max_range: 30.0
                  normalize: true
