scenario:
  name: gaplock_dqn
  env:
    seed: 42
    n_agents: 2
    max_steps: 10000

    lidar_beams: 54
    # vehicle_params:
    #   v_min: -2.0
    #   v_max: 10.0
    map_dir: maps
    map_yaml: shanghai/Shanghai_map.yaml
    map: shanghai/Shanghai_map.yaml
    map_ext: .png
    centerline_autoload: true
    centerline_render: true
    centerline_features: true
    render_mode: human
    update: 2
    terminate_on_any_done: true
    spawn_points:
      - spawn_1
      - spawn_2

  reward:
    task: gaplock
    params:
      target_crash_reward: 10.0
      self_collision_penalty: -5.0
      truncation_penalty: -1.0
      reward_horizon: 500.0
  main:
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: dqn
      tags:
      - dqn
    mode: train_eval
    save_eval_rollouts: true
    eval_rollout_dir: eval_rollouts
    train_episodes: 1000
    eval_episodes: 1
    checkpoint: checkpoints/dqn_gaplock/dqn_gaplock.pt
  algorithms:
    dqn:
      device: cpu
      lr: 0.0004
      gamma: 0.995
      batch_size: 512
      buffer_size: 200000
      target_update_interval: 500
      epsilon_start: 1.0
      epsilon_end: 0.1
      epsilon_decay_rate: 0.9995
      hidden_dims:
      - 256
      - 256
      prioritized_replay: true
      per_alpha: 0.6
      per_beta_start: 0.4
      per_beta_increment: 5.0e-05
      per_min_priority: 0.001
      per_epsilon: 1.0e-06
      action_mode: rate
      steering_rate: 0.5
      accel_rate: 5.0
      brake_rate: 3.0
      rate_initial_speed: 2.0
      train_episodes: 1000
      eval_episodes: 1
      save_dir: checkpoints/dqn_gaplock
      checkpoint_name: dqn_gaplock.pt
  agents:
    car_1:
      slot: 1
      trainable: true
      wrappers:
      - factory: obs
        params:
          max_scan: 30.0
          normalize: true
          components:
          - id: lidar
            type: lidar
            params:
              beams: 54
              max_range: 30.0
              normalize: true
          - id: ego_pose
            type: ego_pose
            params:
              normalize_xy: 30.0
              angle_mode: sin
          - id: ego_collision
            type: collision
          - id: target_pose
            type: target_pose
            target:
              agent: car_0
          - id: target_collision
            type: collision
            target:
              agent: car_0
      algo: dqn
      config_ref: dqn
      agent_id: car_1
    
    car_0:
      algo: follow_gap
      slot: 0
      trainable: false
      params:
        max_speed: 18.0
        min_speed: 2.0
        steering_gain: 0.95
        bubble_radius: 4
        steer_smooth: 0.0
      agent_id: car_0
      wrappers:
      - factory: obs
        params:
          max_scan: 30.0
          normalize: true
          components:
          - id: lidar
            type: lidar
            params:
              beams: 54
              max_range: 30.0
              normalize: true
