meta:
  name: kamikaze_sac

scenario:
  env:
    map: line2
    seed: 7
    max_steps: 1500
    lidar_beams: 108
    terminate_on_any_done: true
    vehicle_params:
      v_max: 1.0
      v_min: -1.0
      length: 0.32
      width: 0.225
    spawn_points:
      - spawn_2
      - spawn_1
    spawn_point_sets:
      - id: offset_lane_a
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_3
          - spawn_1
      - id: offset_lane_b
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_2
          - spawn_1
      - id: extended_gap
        metadata:
          spawn_option_id: spawn_random
        names:
          - spawn_4
          - spawn_1
    spawn_curriculum:
      min_episode: 0
      activation_samples: 40
      success_window: 8
      enable_rate: 0.7
      enable_patience: 4
      disable_rate: 0.3
      disable_patience: 2
      cooldown: 20
      persist: true
      start_enabled: true

  main:
    mode: train
    train_episodes: 1500
    eval_episodes: 10
    eval_interval: 150
    federated:
      enabled: false
      interval: 50
      agents:
        - car_0
      root: outputs/kamikaze_sac
      mode: mean
      timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/kamikaze_sac/kamikaze_sac.pt
    warm_start_checkpoint: warm_starts/sac_best_eager-sweep-5.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: kamikaze_sac
      tags:
        - sac
        - kamikaze

  agents:
    car_0:
      trainable: true
      algorithm:
        name: sac
        params:
          device: cuda
          actor_lr: 0.003
          critic_lr: 0.0045
          alpha_lr: 0.003
          gamma: 0.99
          tau: 0.005
          batch_size: 256
          buffer_size: 250000
          warmup_steps: 15000
          auto_alpha: true
          target_entropy: -2.2
          hidden_dims:
            - 512
            - 256
            - 128
          exploration_noise: 0.2
          exploration_noise_final: 0.05
          exploration_noise_decay_steps: 450000
          initial_speed: 0.9
          initial_speed_warmup_steps: 180
          initial_speed_warmup_throttle: 0.5
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.4
          per_beta_final: 1.0
          per_beta_increment: 1e-6
          per_min_priority: 1e-3
          per_epsilon: 1e-6
      reward:
        task: kamikaze
        params:
          target_agent: car_1
          success_reward: 150.0
          step_penalty: -0.001
          self_collision_penalty: -5.0
          success_once: true
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 108
                  max_range: 30.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_distance: 30.0
          window_size: 2
          bubble_radius: 1
          max_steer: 0.35
          min_speed: 0.2
          max_speed: 1.0
          steering_gain: 0.4
          fov_deg: 270
          normalized: true
          steer_smooth: 0.35
          center_bias_gain: 0.09
          inside_bias_gain: 0.2
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
      policy_curriculum:
        success_window: 40
        activation_samples: 30
        cooldown: 25
        persist: true
        stages:
          - name: tier0_dumb_defender
            params:
              max_speed: 1.0
              min_speed: 0.35
              steering_gain: 0.25
              steer_smooth: 0.5
              crawl_steer_ratio: 0.55
              center_bias_gain: 0.0
              inside_bias_gain: 0.0
              preview_horizon: 0.0
              preview_samples: 0
              dwa_samples: 0
              enhanced_gap_scoring: false
              u_shape_enabled: false
          - name: tier1_preview_defender
            enable_rate: 0.3
            enable_patience: 3
            params:
              max_speed: 1.0
              min_speed: 0.3
              steering_gain: 0.32
              steer_smooth: 0.42
              crawl_steer_ratio: 0.45
              center_bias_gain: 0.05
              inside_bias_gain: 0.1
              preview_horizon: 0.8
              preview_samples: 5
              dwa_samples: 0
              enhanced_gap_scoring: true
              dwa_horizon: 0.5
              dwa_heading_weight: 0.2
              u_shape_enabled: false
          - name: tier2_top_defender
            enable_rate: 0.55
            enable_patience: 4
            params:
              max_distance: 30.0
              window_size: 2
              bubble_radius: 1
              max_steer: 0.35
              min_speed: 0.2
              max_speed: 1.0
              steering_gain: 0.4
              fov_deg: 270
              normalized: true
              steer_smooth: 0.35
              center_bias_gain: 0.09
              inside_bias_gain: 0.2
              crawl_steer_ratio: 0.35
              steering_speed_scale: 1.0
              preview_horizon: 1.5
              preview_samples: 7
              dwa_samples: 5
              dwa_horizon: 0.5
              dwa_heading_weight: 0.15
              enhanced_gap_scoring: true
              gap_score_width_weight: 1.0
              gap_score_clearance_weight: 1.2
              gap_score_center_weight: 0.5
              gap_score_curvature_weight: 0.2
              u_shape_enabled: false
