includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_centerline_pressure.yaml
- ../configs/observations/centerline_gaplock.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/agents/action_constraints.yaml
- ../configs/evaluation/line2_gaplock_eval_standard.yaml
- ../configs/wandb.yaml
experiment:
  name: ppo
  episodes: 2000
  seed: 42
environment:
  max_steps: 1200
  action_repeat: 2
agents:
  car_0:
    role: attacker
    algorithm: sb3_ppo
    target_id: car_1
    params:
      learning_rate: 0.0003
      gamma: 0.998
      n_steps: 2048
      n_epochs: 10
      gae_lambda: 0.95
      clip_range: 0.2
      ent_coef: 0.0
      activation: tanh
      pi_hidden_dims:
      - 128
      - 128
      vf_hidden_dims:
      - 256
      - 256
      batch_size: 256
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - ppo
  - comparison
  - gaplock
  notes: "PPO curriculum for gaplock adversarial task (use run_sb3.py)"
  mode: online
