includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_centerline_pressure.yaml
- ../configs/observations/centerline_gaplock.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/agents/action_constraints.yaml
- ../configs/evaluation/line2_gaplock_eval_standard.yaml
- ../configs/wandb.yaml
experiment:
  name: ppo_centerline
  episodes: 2000
  seed: 42
environment:
  max_steps: 1200
  action_repeat: 2
  num_agents: 2
agents:
  car_0:
    algorithm: sb3_ppo
    target_id: car_1
    params:
      learning_rate: 0.0001
      gamma: 0.998
      n_steps: 2048
      n_epochs: 10
      gae_lambda: 0.95
      clip_range: 0.2
      ent_coef: 0.0
      activation: tanh
      pi_hidden_dims:
      - 32
      - 32
      vf_hidden_dims:
      - 64
      - 64
      batch_size: 256
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved

  - ppo
  - comparison
  - gaplock
  notes: "PPO"
  mode: online