includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased_full.yaml
- ../configs/evaluation/line2_gaplock_eval_curriculum.yaml
- ../configs/wandb.yaml
experiment:
  name: sac
  episodes: 10000
  seed: 42
environment:
  action_repeat: 2
  max_steps: 1200
agents:
  car_0:
    role: attacker
    algorithm: sb3_sac
    target_id: car_1
    params:
      # SB3 SAC parameters (using proven SB3 defaults)
      learning_rate: 0.0003
      gamma: 0.99
      tau: 0.005
      ent_coef: auto  # Automatic entropy tuning
      target_entropy: auto
      hidden_dims:
      - 64
      - 64
      activation: relu
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 100
      per:
        enabled: true
        alpha: 0.6
        beta: 0.4
        beta_final: 1.0
        beta_anneal_steps: 200000
        epsilon: 1.0e-6
        max_priority: 1.0
        normalize_weights: true
      her:
        enabled: true
        reward_mode: replace
        success_mode: distance
        distance_threshold: 1.0
        success_reward: 0.0
        failure_reward: -1.0
        done_on_success: true
        probability: 1.0
      train_freq: 1  # Train every step (off-policy continuous)
      gradient_steps: 1  # Number of gradient steps per environment step
    observation:
      preset: gaplock
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  tags:
  - improved
  - curriculum_v2
  - sac
  - comparison
  - gaplock
  notes: SAC curriculum for gaplock adversarial task
  mode: online
