includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_centerline_pressure.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/agents/action_constraints.yaml
- ../configs/evaluation/line2_gaplock_eval_standard.yaml
- ../configs/wandb.yaml
experiment:
  name: sac
  episodes: 2000
  seed: 42
environment:
  max_steps: 2000
  action_repeat: 2
  centerline_autoload: true
  spawn_centerline:
    min_distance_m: 5.0
    max_distance_m: 5.0
  random_spawn:
    enabled: true
    mode: target_relative
    target_agent: car_1
    target_on_centerline: true
    offsets:
      # x_range_behind:
      # - -0.05
      # - 0.0
      x_range_front:
      - 1.5
      - 0.5
      y_range_left:
      - -0.35
      - -0.0
      y_range_right:
      - 0.0
      - 0.35
      theta_range:
      - -0.2
      - 0.2
      frame: target
    min_separation: 0.3
    min_wall_distance: 0.3
    reject_offtrack: true
    max_attempts: 50
agents:
  car_0:
    role: attacker
    algorithm: sb3_sac
    target_id: car_1
    params:
      device: cuda
      learning_rate: 0.0003
      gamma: 0.99
      tau: 0.005
      ent_coef: auto
      target_entropy: auto
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 1000
      train_freq: 1
      gradient_steps: 1
      activation: relu
      hidden_dims:
      - 256
      - 256
    observation:
      preset: gaplock
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - sac
  - comparison
  - gaplock
  notes: "SAC for gaplock adversarial task (use run_v2.py)"
  mode: online
