meta:
  name: sac_buda

scenario:
  env:
    map: Budapest_map
    seed: 42
    max_steps: 15000
    lidar_beams: 108
    terminate_on_any_done: true
    vehicle_params:
      v_max: 10.0
      v_min: -1.0
      length: 0.32
      width: 0.225
    spawn_points:
      - spawn_1
      - spawn_2
    spawn_point_sets:
      - id: a
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 1
        names:
          - spawn_1
          - spawn_3
      - id: b
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 2
        names:
          - spawn_1
          - spawn_4
      - id: c
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 3
        names:
          - spawn_1
          - spawn_5
      - id: d
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 4
        names:
          - spawn_1
          - spawn_6
      - id: e
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 5
        names:
          - spawn_1
          - spawn_7
      - id: f
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 6
        names:
          - spawn_1
          - spawn_8
      - id: g
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 7
        names:
          - spawn_1
          - spawn_9
      - id: h
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 8
        names:
          - spawn_1
          - spawn_10
      - id: i
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 9
        names:
          - spawn_1
          - spawn_11
      - id: j
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 10
        names:
          - spawn_1
          - spawn_12
      - id: k
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 11
        names:
          - spawn_1
          - spawn_13
      - id: l
        metadata:
          spawn_option_id: spawn_random
          spawn_curriculum_stage: 12
        names:
          - spawn_1
          - spawn_14
    spawn_curriculum:
      min_episode: 0
      activation_samples: 10
      success_window: 8
      enable_rate: 0.7
      enable_patience: 4
      disable_rate: 0.3
      disable_patience: 2
      cooldown: 20
      persist: true
      start_enabled: false
      stages:
        - name: buda_inner_lane
          max_stage: 1
          enable_rate: 0.72
          enable_patience: 3
        - name: buda_mid_lane
          max_stage: 2
          enable_rate: 0.78
          enable_patience: 3
        - name: buda_outer_lane
          max_stage: 3
          enable_rate: 0.85
          enable_patience: 4

  main:
    mode: train
    train_episodes: 1500
    eval_episodes: 0
    eval_interval: 0
    federated:
      enabled: false
      interval: 50
      agents:
        - car_0
      root: outputs/buda_sac
      mode: mean
      timeout: 600.0
    save_eval_rollouts: false
    eval_rollout_dir: eval_rollouts
    checkpoint: checkpoints/buda_sac/buda_sac.pt
    warm_start_checkpoint: warm_starts/sac_best_sac_buda-r01-e37dfb35.pt
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: buda_sac
      tags:
        - buda_sac

  agents:
    car_0:
      trainable: true
      algorithm:
        name: sac
        params:
          device: cpu
          actor_lr: 0.003
          critic_lr: 0.0045
          alpha_lr: 0.003
          gamma: 0.99
          tau: 0.005
          batch_size: 256
          buffer_size: 250000
          warmup_steps: 15000
          auto_alpha: true
          target_entropy: -2.2
          hidden_dims:
            - 512
            - 256
            - 128
          exploration_noise: 0.2
          exploration_noise_final: 0.05
          exploration_noise_decay_steps: 450000
          initial_speed: 1.9
          initial_speed_warmup_steps: 180
          initial_speed_warmup_throttle: 0.5
          prevent_reverse: true
          prevent_reverse_min_speed: 0.01
          prevent_reverse_speed_index: 1
          include_truncation: true
          use_per: true
          per_alpha: 0.6
          per_beta_start: 0.4
          per_beta_final: 1.0
          per_beta_increment: 1e-6
          per_min_priority: 1e-3
          per_epsilon: 1e-6
      reward:
        task: kamikaze
        params:
          # Target agent ID that should be forced to crash; defaults to "car_1".
          target_agent: car_1
          # Reward bonus granted once the target collides (even if the attacker does too).
          success_reward: 150.0
          # When true, only award the bonus the first time this attacker tags the target.
          success_once: true
          # Small per-step shaping term to discourage long chases (negative values penalise time).
          step_penalty: -0.0001
          # Penalty applied if the attacker crashes without the target going down.
          self_collision_penalty: -15.0
          # Per-second shaping bonus when staying within 2 m of the defender (linearly fades until far distance).
          distance_reward_near: 0.04
          distance_reward_near_distance: 2.0
          # Per-second penalty when the defender opens up more than 5 m of space.
          distance_penalty_far: 0.03
          distance_reward_far_distance: 5.0
          # One-time bonus for breaching a 0.5 m bubble around the defender (encourages final dive).
          radius_bonus_reward: 35.0
          radius_bonus_distance: 0.5
          radius_bonus_once: true
          # Scales reward by how much the attacker closes distance compared to the previous step (per meter).
          distance_delta_reward: 2.0
          # Idle guard rails: penalize if speed stays below the threshold for consecutive steps.
          idle_penalty: -0.25
          idle_penalty_steps: 80
          idle_speed_threshold: 0.2
      wrappers:
        - factory: obs
          params:
            max_scan: 10.0
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 108
                  max_range: 10.0
                  normalize: true
                  clip: 1.0
              - id: ego_pose
                type: ego_pose
                params:
                  angle_mode: sin_cos
              - id: ego_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
              - id: target_pose
                type: target_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1
              - id: target_vel
                type: velocity
                params:
                  normalize: 2.0
                  include_speed: true
                  speed_scale: 1.0
                target:
                  agent: car_1
              - id: relative_pose
                type: relative_pose
                params:
                  angle_mode: sin_cos
                target:
                  agent: car_1

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_distance: 10.0
          window_size: 2
          bubble_radius: 1
          max_steer: 0.35
          min_speed: 0.2
          max_speed: 2.0
          steering_gain: 0.4
          fov_deg: 270
          normalized: true
          steer_smooth: 0.35
          center_bias_gain: 0.09
          inside_bias_gain: 0.2
          crawl_steer_ratio: 0.35
          steering_speed_scale: 1.0
          preview_horizon: 1.5
          preview_samples: 7
          dwa_samples: 5
          dwa_horizon: 0.5
          dwa_heading_weight: 0.15
          enhanced_gap_scoring: true
          gap_score_width_weight: 1.0
          gap_score_clearance_weight: 1.2
          gap_score_center_weight: 0.5
          gap_score_curvature_weight: 0.2
          u_shape_enabled: false
     
