scenario:
  name: shanghai_dqn_progress
  env:
    seed: 42
    n_agents: 4
    max_steps: 25000
    lidar_beams: 108
    map_dir: maps
    map_yaml: shanghai/Shanghai_map.yaml
    target_laps: 2
    centerline_render: false
    centerline_features: true
    spawn_points:
      - spawn_1
      - spawn_2
      - spawn_3
      - spawn_4
  reward:
    task: progress
    params:
      progress_weight: 3.5
      speed_weight: 0.01
      lateral_penalty: 0.01
      heading_penalty: 0.01
      collision_penalty: -5.5
      truncation_penalty: -1.5
  main:
    mode: train_eval
    train_episodes: 500
    eval_episodes: 2
    checkpoint: checkpoints/shanghai_progress/shanghai_dqn_progress.pt
  algorithms:
    dqn:
      device: cpu
      lr: 0.001
      gamma: 0.995
      batch_size: 512
      buffer_size: 200000
      target_update_interval: 10
      epsilon_start: 0.998
      epsilon_end: 0.05
      epsilon_decay_rate: 0.995
      hidden_dims:
        - 256
        - 128
      prioritized_replay: true
      per_alpha: 0.6
      per_beta_start: 0.4
      per_beta_increment: 5.0e-05
      per_min_priority: 0.001
      per_epsilon: 1.0e-06
      action_mode: rate
      steering_rate: 0.45
      accel_rate: 3.0
      brake_rate: 2.5
      rate_initial_speed: 1.0
      save_dir: checkpoints/shanghai_progress
      checkpoint_name: shanghai_dqn_progress.pt
  agents:
    car_0:
      wrappers: &car_obs_wrappers
        - factory: obs
          params:
            normalize: true
            components:
              - id: lidar
                type: lidar
                params:
                  beams: 108
                  max_range: 30.0
                  normalize: true
              - id: ego_pose
                type: ego_pose
              - id: collision
                type: collision
      algo: dqn
    car_1:
      wrappers: *car_obs_wrappers
      algo: dqn
    car_2:
      wrappers: *car_obs_wrappers
      algo: dqn
    car_3:
      wrappers: *car_obs_wrappers
      algo: dqn
