includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased_full.yaml
- ../configs/evaluation/line2_gaplock_eval_curriculum.yaml
- ../configs/wandb.yaml
experiment:
  name: td3
  episodes: 2000
  seed: 42
environment:
  action_repeat: 2
agents:
  car_0:
    role: attacker
    algorithm: sb3_td3
    target_id: car_1
    params:
      learning_rate: 0.0001
      gamma: 0.995
      tau: 0.01
      hidden_dims:
      - 256
      - 256
      activation: relu
      pi_hidden_dims: null
      qf_hidden_dims: null
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 1000
      policy_delay: 2
      target_policy_noise: 0.2
      target_noise_clip: 0.5
      action_noise_sigma: 0.1
      her:
        enabled: true
        reward_mode: replace
        success_mode: distance
        distance_threshold: 1.0
        success_reward: 0.0
        failure_reward: -1.0
        done_on_success: true
        probability: 1.0
    observation:
      preset: gaplock
    frame_stack: 1
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - td3
  - comparison
  - gaplock
  notes: SAC curriculum for gaplock adversarial task
  mode: online
