meta:
  name: template_experiment

scenario:
  env:
    map: bundle_name_here
    seed: 42
    max_steps: 10000

  main:
    mode: train_eval
    train_episodes: 1000
    eval_episodes: 10

  agents:
    car_0:
      trainable: true
      algorithm:
        name: dqn
        params:
          device: cpu
          lr: 0.0003
          gamma: 0.99
          batch_size: 512
          buffer_size: 200000
          target_update_interval: 500
          epsilon_start: 1.0
          epsilon_end: 0.05
          epsilon_decay_rate: 0.999
          hidden_dims:
            - 256
            - 256
      reward:
        task: gaplock
        params:
          target_crash_reward: 10.0
          self_collision_penalty: -1.0
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            components:
              - id: lidar
                type: lidar
              - id: ego_pose
                type: ego_pose

    car_1:
      trainable: false
      algorithm:
        name: follow_gap
        params:
          max_speed: 18.0
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
