includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased_quick.yaml
- ../configs/evaluation/line2_gaplock_eval_standard.yaml
- ../configs/wandb.yaml
experiment:
  name: tqc
  episodes: 1500
  seed: 42
environment:
  max_steps: 2500
agents:
  car_0:
    role: attacker
    algorithm: sb3_tqc
    target_id: car_1
    params:
      learning_rate: 0.0003
      gamma: 0.995
      tau: 0.005
      ent_coef: auto
      target_entropy: auto
      top_quantiles_to_drop_per_net: 2
      hidden_dims:
      - 256
      - 256
      activation: relu
      pi_hidden_dims: null
      qf_hidden_dims: null
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 1000
      train_freq: 1  # Train every step (off-policy continuous)
      gradient_steps: 1  # Number of gradient steps per environment step
    observation:
      preset: gaplock
    reward:
      preset: gaplock_full
      overrides:
        forcing:
          enabled: true
          pinch_pockets:
            enabled: true
            anchor_forward: 1.2
            anchor_lateral: 0.35
            sigma: 0.55
            weight: 0.004
            peak: 1.0
            floor: -0.5
            power: 2.0
          clearance:
            enabled: true
            weight: 0.003
            band_min: 0.3
            band_max: 3.2
            clip: 0.015
            time_scaled: true
          turn:
            enabled: true
            weight: 0.006
            clip: 0.015
            time_scaled: true
        distance:
          enabled: false
          near_distance: 1.0
          far_distance: 2.5
          reward_near: 0.004
          penalty_far: 0.002
        heading:
          enabled: true
          coefficient: 0.001
        speed:
          enabled: true
          bonus_coef: 0.0005
        step_reward: -0.001
        terminal:
          target_crash: 50.0  # Success bonus (was 200.0 - too large, causing training instability)
          self_crash: -40.0   # Failure penalty (was -20.0 - too lenient)
          timeout: -15.0      # Timeout penalty (was -100.0 - too severe)
          collision: 0.0      # Handled via self_crash/target_crash
  car_1:
    role: defender
    algorithm: ftg
    params:
      max_distance: 12.0
      window_size: 4
      bubble_radius: 3
      max_steer: 0.42
      min_speed: 0.2
      max_speed: 1.0
      steering_gain: 0.35
      fov: 4.71238898
      normalized: false
      steer_smooth: 0.6
      mode: lidar
      gap_min_range: 0.4
      target_mode: center
      wall_avoid_kick: 0.02
      panic_factor_near: 1.0
      panic_factor_very_near: 1.0
      use_disparity_extender: true
      disparity_threshold: 0.35
      vehicle_width: 0.225
      safety_margin: 0.08
      no_cutback_enabled: true
      cutback_clearance: 0.9
      cutback_hold_steps: 8
    ftg_schedule:
      enabled: true
      by_stage:
        optimal_varied_speed:
          max_speed: 0.6
          steering_gain: 0.4
          steer_smooth: 0.4
          bubble_radius: 2.5
          safety_margin: 0.1
          gap_min_range: 0.55
          target_mode: center
          wall_avoid_kick: 0.05
          panic_factor_near: 1.1
          panic_factor_very_near: 1.25
        full_random:
          max_speed: 1.0
          steering_gain: 0.6
          steer_smooth: 0.3
          bubble_radius: 3.0
          safety_margin: 0.15
          gap_min_range: 0.65
          target_mode: farthest
          wall_avoid_kick: 0.12
          panic_factor_near: 1.2
          panic_factor_very_near: 1.4

# Evaluation configuration (optional)
# Uncomment to enable periodic evaluation during training
evaluation:
  enabled: true
  frequency: 100  # Run evaluation every 100 training episodes
  num_episodes: 12  # Number of episodes per evaluation run
  deterministic: true  # Use deterministic actions
  spawn_points: [spawn_pinch_left, spawn_pinch_right, spawn_pinch_ahead, spawn_approach_0.0C, spawn_approach_0.3L, spawn_approach_0.3R]  # Sequential fixed spawns
  spawn_speeds: [0.0, 0.0]  # Initial speeds for each spawn point
  lock_speed_steps: 0  # No speed locking during eval
  ftg_override:  # Full FTG strength for evaluation
    max_speed: 1.0
    bubble_radius: 3.0
    steering_gain: 0.35

# Systematic Phased Curriculum - Progressive Difficulty Scaling
# Group 1: Lock Speed Reduction (7 phases)
# Group 2: Speed Reduction (6 phases)
# Group 3: Spatial Introduction (5 phases)
# Group 4: FTG Hardening (8 phases)
curriculum:
  type: phased
  start_phase: 0

  phases:
    # ==================== GROUP 1: LOCK SPEED REDUCTION ====================
    # Gradually reduce speed lock while keeping everything else constant

    - name: "1_foundation_lock800"
      description: "Foundation - Lock 800 steps"
      criteria:
        success_rate: 0.70
        avg_reward: 50.0
        min_episodes: 100
        patience: 500
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 800
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0

    - name: "1_lock600"
      description: "Lock 600 steps"
      criteria:
        success_rate: 0.68
        min_episodes: 75
        patience: 350
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 600
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.10

    - name: "1_lock400"
      description: "Lock 400 steps"
      criteria:
        success_rate: 0.66
        min_episodes: 75
        patience: 350
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 400
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.10
      keep_previous: 0.15

    - name: "1_lock200"
      description: "Lock 200 steps"
      criteria:
        success_rate: 0.64
        min_episodes: 75
        patience: 350
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 200
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.12
      keep_previous: 0.18

    - name: "1_lock100"
      description: "Lock 100 steps"
      criteria:
        success_rate: 0.62
        min_episodes: 75
        patience: 400
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 100
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.12
      keep_previous: 0.20

    - name: "1_lock50"
      description: "Lock 50 steps"
      criteria:
        success_rate: 0.60
        min_episodes: 75
        patience: 400
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 50
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.15
      keep_previous: 0.20

    - name: "1_lock0"
      description: "No speed lock"
      criteria:
        success_rate: 0.58
        min_episodes: 75
        patience: 400
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.15
      keep_previous: 0.22

    # ==================== GROUP 2: SPEED REDUCTION ====================
    # Gradually reduce defender start speed to zero

    - name: "2_speed035"
      description: "Reduce speed to 0.35"
      criteria:
        success_rate: 0.60
        min_episodes: 75
        patience: 400
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.35, 0.35]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.15
      keep_previous: 0.22

    - name: "2_speed025"
      description: "Reduce speed to 0.25"
      criteria:
        success_rate: 0.65
        min_episodes: 75
        patience: 400
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.25, 0.25]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.18
      keep_previous: 0.22

    - name: "2_speed015"
      description: "Reduce speed to 0.15"
      criteria:
        success_rate: 0.70
        min_episodes: 75
        patience: 400
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.15, 0.15]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.18
      keep_previous: 0.25

    - name: "2_speed005"
      description: "Reduce speed to 0.05"
      criteria:
        success_rate: 0.75
        min_episodes: 75
        patience: 450
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.05, 0.05]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    - name: "2_speed_var_low"
      description: "Low speed variation (0.0-0.10)"
      criteria:
        success_rate: 0.70
        min_episodes: 75
        patience: 450
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.0, 0.10]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    - name: "2_speed000"
      description: "Speed at 0.0"
      criteria:
        success_rate: 0.75
        min_episodes: 100
        patience: 500
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    # ==================== GROUP 3: SPATIAL INTRODUCTION ====================
    # Add spawn points one by one

    - name: "3_add_pinch_ahead"
      description: "Add spawn_pinch_ahead (3 spawns)"
      criteria:
        success_rate: 0.70
        min_episodes: 100
        patience: 450
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead]
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    - name: "3_add_approach_center"
      description: "Add spawn_approach_0.0C (4 spawns)"
      criteria:
        success_rate: 0.65
        min_episodes: 100
        patience: 500
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead,
                 spawn_approach_0.0C]
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    - name: "3_add_approach_left"
      description: "Add spawn_approach_0.3L (5 spawns)"
      criteria:
        success_rate: 0.60
        min_episodes: 100
        patience: 500
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead,
                 spawn_approach_0.0C, spawn_approach_0.3L]
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.22
      keep_previous: 0.25

    - name: "3_add_approach_right"
      description: "Add spawn_approach_0.3R (6 spawns)"
      criteria:
        success_rate: 0.55
        min_episodes: 125
        patience: 550
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead,
                 spawn_approach_0.0C, spawn_approach_0.3L, spawn_approach_0.3R]
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.22
      keep_previous: 0.25

    - name: "3_all_spawns"
      description: "All spawn points"
      criteria:
        success_rate: 0.50
        min_episodes: 150
        patience: 600
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.25
      keep_previous: 0.25

    # ==================== GROUP 4: FTG HARDENING ====================
    # Gradually increase FTG difficulty

    - name: "4_ftg_very_light"
      description: "Very light FTG (gain=0.30)"
      criteria:
        success_rate: 0.48
        min_episodes: 125
        patience: 550
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.30
        bubble_radius: 2.2
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_light"
      description: "Light FTG (gain=0.35)"
      criteria:
        success_rate: 0.45
        min_episodes: 125
        patience: 600
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.35
        bubble_radius: 2.4
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_moderate_low"
      description: "Moderate-low FTG (gain=0.40)"
      criteria:
        success_rate: 0.40
        min_episodes: 125
        patience: 600
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.40
        bubble_radius: 2.6
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_moderate"
      description: "Moderate FTG (gain=0.45)"
      criteria:
        success_rate: 0.35
        min_episodes: 150
        patience: 650
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.45
        bubble_radius: 2.8
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_moderate_high"
      description: "Moderate-high FTG (gain=0.50)"
      criteria:
        success_rate: 0.30
        min_episodes: 150
        patience: 700
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.50
        bubble_radius: 3.0
        target_mode: farthest
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_strong"
      description: "Strong FTG (gain=0.55)"
      criteria:
        success_rate: 0.28
        min_episodes: 150
        patience: 750
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.55
        bubble_radius: 3.2
        target_mode: farthest
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_very_strong"
      description: "Very strong FTG (gain=0.58)"
      criteria:
        success_rate: 0.25
        min_episodes: 150
        patience: 800
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.58
        bubble_radius: 3.4
        target_mode: farthest
      keep_foundation: 0.25
      keep_previous: 0.25

    - name: "4_ftg_expert"
      description: "Expert FTG (gain=0.60) - final challenge"
      criteria:
        success_rate: 0.22
        min_episodes: 200
        patience: 800
      spawn:
        points: all
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.60
        bubble_radius: 3.5
        target_mode: farthest
      keep_foundation: 0.25
      keep_previous: 0.25
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - tqc
  - comparison
  - gaplock
  notes: SAC curriculum for gaplock adversarial task
  mode: online
