includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased.yaml
- ../configs/evaluation/line2_gaplock_eval_curriculum.yaml
- ../configs/wandb.yaml
experiment:
  name: tqc
  episodes: 10000
  seed: 42
environment:
  action_repeat: 2
agents:
  car_0:
    role: attacker
    algorithm: sb3_tqc
    target_id: car_1
    params:
      learning_rate: 0.0003
      gamma: 0.99
      tau: 0.005
      ent_coef: auto
      target_entropy: auto
      top_quantiles_to_drop_per_net: 2
      hidden_dims:
      - 64
      - 64
      activation: relu
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 100
      per:
        enabled: true
        alpha: 0.6
        beta: 0.4
        beta_final: 1.0
        beta_anneal_steps: 200000
        epsilon: 1.0e-6
        max_priority: 1.0
        normalize_weights: true
      her:
        enabled: true
        reward_mode: replace
        success_mode: distance
        distance_threshold: 1.0
        success_reward: 0.0
        failure_reward: -1.0
        done_on_success: true
        probability: 1.0
    observation:
      preset: gaplock
    frame_stack: 4
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - tqc
  - comparison
  - gaplock
  notes: gaplock
  mode: online
