includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased_quick.yaml
- ../configs/wandb.yaml
experiment:
  name: tqc
  episodes: 1500
  seed: 42
environment:
  max_steps: 2500
agents:
  car_0:
    role: attacker
    algorithm: sb3_tqc
    target_id: car_1
    params:
      learning_rate: 0.0003
      gamma: 0.995
      tau: 0.005
      ent_coef: auto
      target_entropy: auto
      top_quantiles_to_drop_per_net: 2
      hidden_dims:
      - 256
      - 256
      activation: relu
      pi_hidden_dims: null
      qf_hidden_dims: null
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 1000
      her:
        enabled: true
        reward_mode: replace
        success_mode: distance
        distance_threshold: 1.0
        success_reward: 0.0
        failure_reward: -1.0
        done_on_success: true
        probability: 1.0
    observation:
      preset: gaplock
    frame_stack: 1
evaluation:
  enabled: true
  frequency: 100
  num_episodes: 12
  deterministic: true
  spawn_points:
  - spawn_pinch_left
  - spawn_pinch_right
  - spawn_pinch_ahead
  spawn_speeds:
  - 0.0
  - 0.0
  lock_speed_steps: 0
  ftg_override:
    max_speed: 1.0
    bubble_radius: 2.6
    steering_gain: 0.4
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - tqc
  - comparison
  - gaplock
  notes: SAC curriculum for gaplock adversarial task
  mode: online
