includes:
- ../configs/env/line2_gaplock.yaml
- ../configs/reward/gaplock_attacker.yaml
- ../configs/agents/ftg_defender.yaml
- ../configs/curriculum/line2_gaplock_phased.yaml
- ../configs/evaluation/line2_gaplock_eval_narrow.yaml
- ../configs/wandb.yaml
experiment:
  name: tqc
  episodes: 1500
  seed: 42
agents:
  car_0:
    role: attacker
    algorithm: sb3_tqc
    target_id: car_1
    params:
      learning_rate: 0.0001
      gamma: 0.995
      tau: 0.001
      ent_coef: auto
      target_entropy: auto
      top_quantiles_to_drop_per_net: 2
      hidden_dims:
      - 256
      - 256
      activation: relu
      pi_hidden_dims: null
      qf_hidden_dims: null
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 256
      her:
        enabled: true
        reward_mode: replace
        success_mode: distance
        distance_threshold: 1.0
        success_reward: 0.0
        failure_reward: -1.0
        done_on_success: true
        probability: 1.0
    observation:
      preset: gaplock
    frame_stack: 1
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  name: null
  group: null
  job_type: null
  tags:
  - improved
  - curriculum_v2
  - tqc
  - comparison
  - gaplock
  notes: gaplock
  mode: online
