experiment:
  name: tqc
  episodes: 1500
  seed: 42
environment:
  map: maps/line2/line2.yaml
  num_agents: 2
  max_steps: 1500
  lidar_beams: 108
  spawn_points:
  - spawn_2
  - spawn_1
  timestep: 0.01
  render: false
  spawn_configs:
    spawn_pinch_right:
      car_0:
      - -45.569
      - -1.0
      - 0.2
      car_1:
      - -46.769
      - -0.7
      - 0.0
    spawn_pinch_left:
      car_0:
      - -45.569
      - -0.4
      - -0.2
      car_1:
      - -46.769
      - -0.7
      - 0.0
    spawn_pinch_ahead:
      car_0:
      - -45.569
      - -0.7
      - 0.0
      car_1:
      - -46.769
      - -0.7
      - 0.0
    spawn_approach_0.0C:
      car_0:
      - -45.569
      - -0.7
      - 0.0
      car_1:
      - -46.769
      - -0.7
      - 0.0
    spawn_approach_0.3L:
      car_0:
      - -45.569
      - -0.4
      - 0.0
      car_1:
      - -46.769
      - -0.7
      - 0.0
    spawn_approach_0.3R:
      car_0:
      - -45.569
      - -1.0
      - 0.0
      car_1:
      - -46.769
      - -0.7
      - 0.0
  visualization:
    reward_ring:
      enabled: false
      preferred_radius: 1.5
    heatmap:
      enabled: false
      extent_m: 6.0
      cell_size_m: 0.25
      alpha: 0.22
      update_frequency: 5
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0
agents:
  car_0:
    role: attacker
    algorithm: sb3_tqc
    target_id: car_1
    params:
      # SB3 TQC parameters (using proven SB3 defaults)
      learning_rate: 0.0001
      gamma: 0.995
      tau: 0.01
      ent_coef: auto  # Automatic entropy tuning
      target_entropy: auto
      top_quantiles_to_drop_per_net: 2
      hidden_dims:
      - 256
      - 256
      buffer_size: 1000000
      batch_size: 256
      learning_starts: 1000
      her:
        enabled: true
        reward_mode: bonus
        distance_threshold: 1.0
        success_reward: 0.004
        failure_reward: 0.0
        done_on_success: false
        probability: 1.0
    observation:
      preset: gaplock
    reward:
      preset: gaplock_full
      overrides:
        forcing:
          enabled: true
          pinch_pockets:
            enabled: true
            anchor_forward: 1.2
            anchor_lateral: 0.35
            sigma: 0.55
            weight: 0.004
            peak: 1.0
            floor: -0.5
            power: 2.0
          clearance:
            enabled: true
            weight: 0.003
            band_min: 0.3
            band_max: 3.2
            clip: 0.015
            time_scaled: true
          turn:
            enabled: true
            weight: 0.006
            clip: 0.015
            time_scaled: true
        distance:
          enabled: false
          near_distance: 1.0
          far_distance: 2.5
          reward_near: 0.004
          penalty_far: 0.002
        heading:
          enabled: true
          coefficient: 0.001
        speed:
          enabled: true
          bonus_coef: 0.0005
        step_reward: -0.001
        terminal:
          target_crash: 200.0
          self_crash: -20.0
          timeout: -100.0
          collision: 0.0
  car_1:
    role: defender
    algorithm: ftg
    params:
      max_distance: 12.0
      window_size: 4
      bubble_radius: 3
      max_steer: 0.42
      min_speed: 0.2
      max_speed: 1.0
      steering_gain: 0.35
      fov: 4.71238898
      normalized: false
      steer_smooth: 0.6
      mode: lidar
      gap_min_range: 0.4
      target_mode: center
      wall_avoid_kick: 0.02
      panic_factor_near: 1.0
      panic_factor_very_near: 1.0
      use_disparity_extender: true
      disparity_threshold: 0.35
      vehicle_width: 0.225
      safety_margin: 0.08
      no_cutback_enabled: true
      cutback_clearance: 0.9
      cutback_hold_steps: 8
# Evaluation configuration (optional)
# Uncomment to enable periodic evaluation during training
evaluation:
  enabled: true
  frequency: 100  # Run evaluation every 100 training episodes
  num_episodes: 12  # Number of episodes per evaluation run
  deterministic: true  # Use deterministic actions
  spawn_points: [spawn_pinch_left, spawn_pinch_right, spawn_pinch_ahead] 
  spawn_speeds: [0.0, 0.0]  # Initial speeds for each spawn point
  lock_speed_steps: 0  # No speed locking during eval
  ftg_override:  # FTG moderate-low cap for evaluation
    max_speed: 1.0
    bubble_radius: 2.0
    steering_gain: 0.30

# Systematic Phased Curriculum - Progressive Difficulty Scaling
# Group 1: Lock Speed Reduction (7 phases)
# Group 2: Speed Reduction (6 phases)

curriculum:
  type: phased
  start_phase: 0

  phases:
    # ==================== GROUP 1: LOCK SPEED REDUCTION ====================
    # Gradually reduce speed lock while keeping everything else constant

    - name: "1_foundation_lock800"
      description: "Foundation - Lock 800 steps"
      criteria:
        # success_rate: rolling target_crash rate required to advance
        # avg_reward: rolling reward threshold (optional)
        # min_episodes: minimum episodes before any advancement
        # patience: max episodes before forced advancement
        # window_size: rolling window for success_rate
        window_size: 50
        success_rate: 0.70
        avg_reward: 50.0
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 800
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0

    - name: "1_lock600"
      description: "Lock 600 steps"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 600
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.10

    - name: "1_lock400"
      description: "Lock 400 steps"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 400
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.10
      keep_previous: 0.15

    - name: "1_lock200"
      description: "Lock 200 steps"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 200
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.12
      keep_previous: 0.18

    - name: "1_lock100"
      description: "Lock 100 steps"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 100
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.12
      keep_previous: 0.20

    - name: "1_lock50"
      description: "Lock 50 steps"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 50
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.15
      keep_previous: 0.20

    - name: "1_lock0"
      description: "No speed lock"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.44, 0.44]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.15
      keep_previous: 0.22

    # ==================== GROUP 2: SPEED REDUCTION ====================
    # Gradually reduce defender start speed to zero

    - name: "2_speed035"
      description: "Reduce speed to 0.35"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.35, 0.35]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.15
      keep_previous: 0.22

    - name: "2_speed025"
      description: "Reduce speed to 0.25"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.25, 0.25]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.18
      keep_previous: 0.22

    - name: "2_speed015"
      description: "Reduce speed to 0.15"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.15, 0.15]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.18
      keep_previous: 0.25

    - name: "2_speed005"
      description: "Reduce speed to 0.05"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.05, 0.05]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    - name: "2_speed_var_low"
      description: "Low speed variation (0.0-0.10)"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.0, 0.10]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    - name: "2_speed000"
      description: "Speed at 0.0"
      criteria:
        window_size: 50
        success_rate: 0.70
        min_episodes: 50
        patience: 1000000
      spawn:
        points: [spawn_pinch_right, spawn_pinch_left]
        speed_range: [0.0, 0.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
      keep_foundation: 0.20
      keep_previous: 0.25

    # # ==================== GROUP 3: SPATIAL INTRODUCTION ====================
    # # Add spawn points one by one

    # - name: "3_add_pinch_ahead"
    #   description: "Add spawn_pinch_ahead (3 spawns)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead]
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.25
    #     bubble_radius: 2.0
    #   keep_foundation: 0.20
    #   keep_previous: 0.25

    # - name: "3_add_approach_center"
    #   description: "Add spawn_approach_0.0C (4 spawns)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead,
    #              spawn_approach_0.0C]
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.25
    #     bubble_radius: 2.0
    #   keep_foundation: 0.20
    #   keep_previous: 0.25

    # - name: "3_add_approach_left"
    #   description: "Add spawn_approach_0.3L (5 spawns)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead,
    #              spawn_approach_0.0C, spawn_approach_0.3L]
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.25
    #     bubble_radius: 2.0
    #   keep_foundation: 0.22
    #   keep_previous: 0.25

    # - name: "3_add_approach_right"
    #   description: "Add spawn_approach_0.3R (6 spawns)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: [spawn_pinch_right, spawn_pinch_left, spawn_pinch_ahead,
    #              spawn_approach_0.0C, spawn_approach_0.3L, spawn_approach_0.3R]
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.25
    #     bubble_radius: 2.0
    #   keep_foundation: 0.22
    #   keep_previous: 0.25

    # - name: "3_all_spawns"
    #   description: "All spawn points"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: all
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.25
    #     bubble_radius: 2.0
    #   keep_foundation: 0.25
    #   keep_previous: 0.25

    # # ==================== GROUP 4: FTG HARDENING ====================
    # # Gradually increase FTG difficulty

    # - name: "4_ftg_very_light"
    #   description: "Very light FTG (gain=0.30)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: all
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.30
    #     bubble_radius: 2.2
    #   keep_foundation: 0.25
    #   keep_previous: 0.25

    # - name: "4_ftg_light"
    #   description: "Light FTG (gain=0.35)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: all
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.35
    #     bubble_radius: 2.4
    #   keep_foundation: 0.25
    #   keep_previous: 0.25

    # - name: "4_ftg_moderate_low"
    #   description: "Moderate-low FTG (gain=0.40)"
    #   criteria:
    #     window_size: 50
    #     success_rate: 0.70
    #     min_episodes: 50
    #     patience: 1000000
    #   spawn:
    #     points: all
    #     speed_range: [0.0, 0.0]
    #   lock_speed_steps: 0
    #   ftg:
    #     steering_gain: 0.40
    #     bubble_radius: 2.6
    #   keep_foundation: 0.25
    #   keep_previous: 0.25

wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  tags:
  - improved
  - curriculum_v2
  - tqc
  - comparison
  - gaplock
  notes: SAC curriculum for gaplock adversarial task
