scenario:
  name: gaplock_td3
  env:
    seed: 42
    n_agents: 2
    max_steps: 10000
    timestep: 0.01
    integrator: RK4
    render_interval: 0
    vehicle_params:
      v_min: -2.0
      v_max: 10.0
    map_dir: maps
    map_yaml: shanghai/Shanghai_map.yaml
    map: shanghai/Shanghai_map.yaml
    map_ext: .png
    centerline_autoload: true
    centerline_render: true
    centerline_features: true
    render_mode: human
    update: 1
  reward:
    mode: progress
    progress:
      progress_weight: 1.0
      speed_weight: 0.0
      lateral_penalty: 0.05
      heading_penalty: 0.02
  main:
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: td3
      tags:
      - gaplock
      - td3
    mode: train_eval
    save_eval_rollouts: true
    eval_rollout_dir: eval_rollouts
    train_episodes: 100
    eval_episodes: 1
    checkpoint: checkpoints/td3_gaplock.pt
  algorithms:
    td3:
      actor_lr: 0.0003
      critic_lr: 0.001
      device: cuda
      gamma: 0.99
      tau: 0.005
      policy_noise: 0.3
      noise_clip: 0.5
      policy_delay: 2
      batch_size: 512
      buffer_size: 100000
      warmup_steps: 10000
      exploration_noise: 0.25
      exploration_noise_final: 0.05
      exploration_noise_decay_steps: 250000
      hidden_dims:
      - 256
      - 256
      train_episodes: 100
      eval_episodes: 1
      save_dir: checkpoints
      checkpoint_name: td3_gaplock.pt
  agents:
    car_0:
      slot: 0
      role: attacker
      wrappers:
      - factory: obs
        params:
          max_scan: 30.0
          normalize: true
          target_role: defender
      algo: td3
      config_ref: td3
      agent_id: car_0
    car_1:
      algo: follow_gap
      slot: 1
      role: defender
      params:
        max_speed: 18.0
        min_speed: 2.0
        steering_gain: 0.95
        bubble_radius: 4
        steer_smooth: 0.0
      agent_id: car_1
      wrappers:
      - factory: obs
        params:
          max_scan: 30.0
          normalize: true
          target_role: defender
