scenario:
  name: gaplock_td3_starved
  env:
    seed: 42
    n_agents: 2
    max_steps: 800
    timestep: 0.01
    integrator: RK4
    render_interval: 0
    map_dir: maps
    map_yaml: shanghai/Shanghai_map.yaml
    map: shanghai/Shanghai_map.yaml
    map_ext: .png
    render_mode: human
    update: 1
  reward:
    target_crash_reward: 80.0
    ego_collision_penalty: -3.0
    truncation_penalty: 0.0
    success_once: true
    reward_horizon: null
    reward_clip: 50.0
  main:
    wandb:
      enabled: true
      project: marl-f110
      entity: ahoop004-old-dominion-university
      group: td3-starved
      tags:
      - td3
      - starved
    mode: train_eval
    save_eval_rollouts: false
    train_episodes: 150
    eval_episodes: 5
    output_root: outputs
    checkpoint: checkpoints/td3_starved.pt
  algorithms:
    td3:
      actor_lr: 0.0004
      critic_lr: 0.0012
      device: cuda
      gamma: 0.99
      tau: 0.005
      policy_noise: 0.25
      noise_clip: 0.4
      policy_delay: 1
      gradient_steps: 2
      batch_size: 256
      buffer_size: 50000
      warmup_steps: 3000
      exploration_noise: 0.3
      exploration_noise_final: 0.05
      exploration_noise_decay_steps: 50000
      hidden_dims:
      - 256
      - 256
      train_episodes: 150
      eval_episodes: 5
      save_dir: checkpoints
      checkpoint_name: td3_starved.pt
  agents:
    car_0:
      slot: 0
      role: attacker
      wrappers:
      - factory: obs
        params:
          max_scan: 30.0
          normalize: true
          target_role: defender
      algo: td3
      config_ref: td3
      agent_id: car_0
    car_1:
      algo: follow_gap
      slot: 1
      role: defender
      params:
        max_speed: 18.0
        min_speed: 3.0
        steering_gain: 0.85
        bubble_radius: 3
        steer_smooth: 0.45
      agent_id: car_1
      wrappers:
      - factory: obs
        params:
          max_scan: 30.0
          normalize: true
          target_role: defender
  reward_curriculum:
  - mode: basic
    until: 60
  - mode: pursuit
    until: 120
  - mode: adversarial
