# Base layer: common environment defaults shared by most scenarios.

env:
  seed: 42
  n_agents: 2
  max_steps: 10000
  timestep: 0.01
  integrator: RK4
  render_interval: 0
  map_dir: maps
  centerline_autoload: true
  centerline_render: true
  centerline_features: true
  render_mode: human

episodes:
  train: 100
  eval: 1

wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university

main:
  mode: train_eval
  save_eval_rollouts: true
  eval_rollout_dir: eval_rollouts
