device: cpu
lr: 0.0004
gamma: 0.99
batch_size: 512
buffer_size: 100000
target_update_interval: 500
epsilon_start: 1.0
epsilon_end: 0.1
epsilon_decay_rate: 0.9995
hidden_dims: [256, 256]
prioritized_replay: true
per_alpha: 0.6
per_beta_start: 0.4
per_beta_increment: 0.00005
per_min_priority: 0.001
per_epsilon: 1.0e-6
action_mode: rate
steering_rate: 0.5
accel_rate: 2.0
brake_rate: 4.0
rate_initial_speed: 0.0
train_episodes: 100
eval_episodes: 1
save_dir: checkpoints
checkpoint_name: dqn_latest.pt
