actor_lr: 0.0003
critic_lr: 0.0005
device: cuda
gamma: 0.99
lam: 0.95
ent_coef: 0.015
ent_coef_schedule:
  start: 0.015
  final: 0.005
  decay_start: 500
  decay_episodes: 1500
clip_eps: 0.2
update_epochs: 10
minibatch_size: 512
train_episodes: 100
eval_episodes: 1
save_dir: checkpoints
checkpoint_name: ppo_latest.pt
