experiment:
  name: gaplock_rainbow_easier
  episodes: 1500
  seed: 42
environment:
  map: maps/line2/line2.yaml
  num_agents: 2
  max_steps: 2000
  lidar_beams: 108
  spawn_points:
  - spawn_2
  - spawn_1
  timestep: 0.01
  render: false
  spawn_curriculum:
    enabled: true
    window: 200
    activation_samples: 50
    min_episode: 50
    enable_patience: 5
    disable_patience: 3
    cooldown: 20
    lock_speed_steps: 300
    stages:
    - name: close_slow
      spawn_points:
      - spawn_pinch_right
      - spawn_pinch_left
      speed_range:
      - 0.3
      - 0.3
      enable_rate: 0.65
    - name: close_varied
      spawn_points:
      - spawn_pinch_ahead
      - spawn_pinch_right
      - spawn_pinch_left
      speed_range:
      - 0.3
      - 0.6
      enable_rate: 0.7
      disable_rate: 0.5
    - name: full_random
      spawn_points: all
      speed_range:
      - 0.3
      - 1.0
      disable_rate: 0.55
    spawn_configs:
      spawn_pinch_right:
        car_0:
        - -45.569
        - -1.0
        - 0.1
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_left:
        car_0:
        - -45.569
        - -0.4
        - -0.1
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_ahead:
        car_0:
        - -45.569
        - -0.7
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0
agents:
  car_0:
    role: attacker
    algorithm: rainbow_dqn
    target_id: car_1
    params:
      lr: 0.0003
      gamma: 0.995
      hidden_dims:
      - 512
      - 256
      buffer_size: 1000000
      success_buffer_size: 200000
      success_buffer_ratio: 0.3
      batch_size: 256
      learning_starts: 2500
      target_update_freq: 1000
      max_grad_norm: 10.0
      use_double_dqn: true
      use_dueling: true
      use_noisy: true
      use_per: true
      use_n_step: true
      use_categorical: true
      n_step: 3
      v_min: -30.0
      v_max: 50.0
      num_atoms: 51
      noisy_sigma: 0.5
      per_alpha: 0.6
      per_beta: 0.4
      per_beta_increment: 0.001
      per_epsilon: 0.01
      epsilon_start: 1.0
      epsilon_end: 0.05
      epsilon_decay_steps: 50000
      action_set:
      - - -1.0
        - 0.3
      - - -1.0
        - 0.65
      - - -1.0
        - 1.0
      - - -0.5
        - 0.3
      - - -0.5
        - 0.65
      - - -0.5
        - 1.0
      - - 0.0
        - 0.3
      - - 0.0
        - 0.65
      - - 0.0
        - 1.0
      - - 0.5
        - 0.3
      - - 0.5
        - 0.65
      - - 0.5
        - 1.0
      - - 1.0
        - 0.3
      - - 1.0
        - 0.65
      - - 1.0
        - 1.0
      prevent_reverse: true
      prevent_reverse_min_speed: 0.01
      prevent_reverse_speed_index: 1
    observation:
      preset: gaplock
    reward:
      preset: gaplock_simple
      overrides:
        terminal:
          target_crash: 200.0
          self_crash: -80.0
          collision: -100.0
          timeout: -40.0
        pressure:
          enabled: true
          distance_threshold: 1.3
          min_speed: 0.25
          heading_tolerance: 1.2
          bonus: 0.02
          bonus_interval: 5
          streak_bonus: 0.01
          streak_cap: 30
        distance:
          enabled: true
          near_distance: 1.2
          far_distance: 2.5
          reward_near: 0.02
          penalty_far: 0.01
        forcing:
          enabled: true
          pinch_pockets:
            enabled: true
            anchor_forward: 1.2
            anchor_lateral: 0.45
            sigma: 0.6
            weight: 0.02
          clearance:
            enabled: true
            weight: 0.015
            band_min: 0.3
            band_max: 3.0
            clip: 0.02
            time_scaled: true
          turn:
            enabled: true
            weight: 0.03
            clip: 0.02
            time_scaled: true
        heading:
          enabled: true
          coefficient: 0.003
        speed:
          enabled: true
          bonus_coef: 0.001
        step_reward: -0.001
  car_1:
    role: defender
    algorithm: ftg
    params:
      max_distance: 12.0
      window_size: 4
      bubble_radius: 2.5
      max_steer: 0.25
      min_speed: 0.15
      max_speed: 0.3
      steering_gain: 0.3
      fov: 4.71238898
      normalized: false
      steer_smooth: 0.4
      mode: lidar
      gap_min_range: 0.65
      target_mode: farthest
      use_disparity_extender: true
      disparity_threshold: 0.35
      vehicle_width: 0.225
      safety_margin: 0.06
      no_cutback_enabled: true
      cutback_clearance: 0.6
      cutback_hold_steps: 8
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  tags:
  - rainbow_dqn
  - easier
  - pursuit
  notes: Rainbow DQN with discrete actions for pursuit task
