experiment:
  name: gaplock_td3_comparison
  episodes: 1500
  seed: 42
environment:
  map: maps/line2/line2.yaml
  num_agents: 2
  max_steps: 2500
  lidar_beams: 720
  spawn_points:
  - spawn_2
  - spawn_1
  timestep: 0.01
  render: false
  spawn_curriculum:
    enabled: true
    window: 200
    activation_samples: 50
    min_episode: 150
    enable_patience: 5
    disable_patience: 3
    cooldown: 20
    lock_speed_steps: 250
    stages:
    - name: optimal_fixed
      spawn_points:
      - spawn_pinch_right
      - spawn_pinch_left
      - spawn_pinch_ahead
      speed_range:
      - 0.5
      - 0.5
      enable_rate: 0.7
    - name: optimal_varied_speed
      spawn_points:
      - spawn_pinch_right
      - spawn_pinch_left
      - spawn_pinch_ahead
      - spawn_approach_0.0C
      - spawn_approach_0.3L
      - spawn_approach_0.3R
      speed_range:
      - 0.3
      - 1.0
      enable_rate: 0.65
      disable_rate: 0.5
    - name: full_random
      spawn_points: all
      speed_range:
      - 0.3
      - 1.0
      disable_rate: 0.45
    spawn_configs:
      spawn_pinch_right:
        car_0:
        - -45.569
        - -1.0
        - 0.1
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_left:
        car_0:
        - -45.569
        - -0.4
        - -0.1
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_ahead:
        car_0:
        - -45.569
        - -0.7
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_approach_0.0C:
        car_0:
        - -49.269
        - -0.7
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_approach_0.3L:
        car_0:
        - -49.269
        - -0.4
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_approach_0.3R:
        car_0:
        - -49.269
        - -1.0
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
  visualization:
    reward_ring:
      enabled: false
      preferred_radius: 1.5
    heatmap:
      enabled: false
      extent_m: 6.0
      cell_size_m: 0.25
      alpha: 0.22
      update_frequency: 5
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0
agents:
  car_0:
    role: attacker
    algorithm: td3
    target_id: car_1
    params:
      lr_actor: 0.0003
      lr_critic: 0.0003
      gamma: 0.995
      tau: 0.005
      policy_noise: 0.2
      noise_clip: 0.5
      policy_delay: 2
      hidden_dims:
      - 256
      - 256
      buffer_size: 1000000
      success_buffer_size: 200000
      success_buffer_ratio: 0.1
      batch_size: 256
      learning_starts: 2500
      exploration_noise: 0.1
      max_grad_norm: 0.5
      use_per: true
      per_alpha: 0.6
      per_beta: 0.4
      per_beta_increment: 0.001
      per_epsilon: 0.01
      prevent_reverse: true
      prevent_reverse_min_speed: 0.01
      prevent_reverse_speed_index: 1
    observation:
      preset: gaplock
    reward:
      preset: gaplock_full
      overrides:
        forcing:
          enabled: true
          pinch_pockets:
            enabled: true
            anchor_forward: 1.2
            anchor_lateral: 0.35
            sigma: 0.55
            weight: 0.004
            peak: 1.0
            floor: -0.5
            power: 2.0
          clearance:
            enabled: true
            weight: 0.003
            band_min: 0.3
            band_max: 3.2
            clip: 0.015
            time_scaled: true
          turn:
            enabled: true
            weight: 0.006
            clip: 0.015
            time_scaled: true
        distance:
          enabled: false
          near_distance: 1.0
          far_distance: 2.5
          reward_near: 0.004
          penalty_far: 0.002
        heading:
          enabled: true
          coefficient: 0.001
        speed:
          enabled: true
          bonus_coef: 0.0005
        step_reward: -0.001
        terminal:
          target_crash: 200.0
          self_crash: -20.0
          timeout: -100.0
          collision: 0.0
  car_1:
    role: defender
    algorithm: ftg
    params:
      max_distance: 12.0
      window_size: 4
      bubble_radius: 2
      max_steer: 0.32
      min_speed: 0.2
      max_speed: 1.0
      steering_gain: 0.6
      fov: 4.71238898
      normalized: false
      steer_smooth: 0.4
      mode: lidar
      gap_min_range: 0.65
      target_mode: farthest
      use_disparity_extender: true
      disparity_threshold: 0.35
      vehicle_width: 0.225
      safety_margin: 0.08
      no_cutback_enabled: true
      cutback_clearance: 0.9
      cutback_hold_steps: 8
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  tags:
  - td3
  - comparison
  - gaplock
  notes: TD3 comparison for gaplock adversarial task
