experiment:
  name: gaplock_ppo_easier
  episodes: 2000
  seed: 42
environment:
  map: maps/line2/line2.yaml
  num_agents: 2
  max_steps: 2000
  lidar_beams: 108
  spawn_points:
  - spawn_2
  - spawn_1
  timestep: 0.01
  render: false
  spawn_curriculum:
    enabled: true
    window: 200
    activation_samples: 50
    min_episode: 50
    enable_patience: 5
    disable_patience: 3
    cooldown: 20
    lock_speed_steps: 250
    stages:
    - name: close_slow
      spawn_points:
      - spawn_pinch_ahead
      speed_range:
      - 0.4
      - 0.4
      enable_rate: 0.65
    - name: close_varied
      spawn_points:
      - spawn_pinch_ahead
      - spawn_pinch_right
      - spawn_pinch_left
      speed_range:
      - 0.4
      - 0.7
      enable_rate: 0.7
      disable_rate: 0.5
    - name: full_random
      spawn_points: all
      speed_range:
      - 0.3
      - 1.0
      disable_rate: 0.55
    spawn_configs:
      spawn_pinch_right:
        car_0:
        - -45.569
        - -1.0
        - 0.1
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_left:
        car_0:
        - -45.569
        - -0.4
        - -0.1
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_ahead:
        car_0:
        - -45.569
        - -0.7
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0
agents:
  car_0:
    role: attacker
    algorithm: ppo
    target_id: car_1
    params:
      lr: 0.0003
      gamma: 0.97
      lam: 0.9
      clip_eps: 0.2
      hidden_dims:
      - 512
      - 512
      update_epochs: 20
      minibatch_size: 256
      batch_size: 4096
      max_grad_norm: 0.5
      normalize_adv: true
      clip_value_loss: true
      vf_coef: 0.5
      ent_coef: 0.05
      ent_coef_schedule:
        start: 0.08
        final: 0.01
        decay_start: 100
        decay_episodes: 800
      episode_batch: false
      prevent_reverse: true
      prevent_reverse_min_speed: 0.01
      prevent_reverse_speed_index: 1
    observation:
      preset: gaplock
    reward:
      preset: gaplock_simple
      overrides:
        penalties:
          enabled: false
        terminal:
          target_crash: 200.0
          self_crash: -20.0
          collision: 0.0
          timeout: -100.0
        pressure:
          enabled: true
          distance_threshold: 1.1
          min_speed: 0.25
          heading_tolerance: 1.0
          bonus: 0.004
          bonus_interval: 5
          streak_bonus: 0.004
          streak_cap: 20
        distance:
          enabled: true
          near_distance: 1.2
          far_distance: 2.5
          reward_near: 0.004
          penalty_far: 0.002
        forcing:
          enabled: true
          pinch_pockets:
            enabled: true
            anchor_forward: 1.2
            anchor_lateral: 0.35
            sigma: 0.6
            weight: 0.004
          clearance:
            enabled: true
            weight: 0.003
            band_min: 0.3
            band_max: 3.0
            clip: 0.02
            time_scaled: true
          turn:
            enabled: true
            weight: 0.006
            clip: 0.02
            time_scaled: true
        heading:
          enabled: true
          coefficient: 0.001
        speed:
          enabled: true
          bonus_coef: 0.0005
        step_reward: -0.001
  car_1:
    role: defender
    algorithm: ftg
    params:
      max_distance: 12.0
      window_size: 4
      bubble_radius: 3.5
      max_steer: 0.3
      min_speed: 0.15
      max_speed: 0.3
      steering_gain: 0.4
      fov: 4.71238898
      normalized: false
      steer_smooth: 0.4
      mode: lidar
      gap_min_range: 0.65
      target_mode: farthest
      use_disparity_extender: true
      disparity_threshold: 0.35
      vehicle_width: 0.225
      safety_margin: 0.12
      no_cutback_enabled: true
      cutback_clearance: 1.0
      cutback_hold_steps: 8
wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  tags:
  - ppo
  - easier
  - pursuit
  notes: PPO training with distance-based pursuit rewards and entropy scheduling
