experiment:
  name: gaplock_ppo_phased_curriculum
  episodes: 5000  # Enough for full curriculum
  seed: 42
  normalize_observations: false

environment:
  map: maps/line2/line2.yaml
  num_agents: 2
  max_steps: 2500
  lidar_beams: 108
  spawn_points:
  - spawn_2
  - spawn_1
  timestep: 0.01
  render: false

  # Base spawn curriculum (will be modified by phased curriculum)
  spawn_curriculum:
    enabled: true
    window: 200
    activation_samples: 50
    min_episode: 50
    enable_patience: 5
    disable_patience: 3
    cooldown: 20
    lock_speed_steps: 800  # Will be overridden by phases
    lock_speed_schedule:
      by_stage:
        optimal_fixed: 800
    stages:
    - name: optimal_fixed
      spawn_points:
      - spawn_pinch_right
      - spawn_pinch_left
      speed_range:
      - 0.44
      - 0.44
      enable_rate: 1.0
    spawn_configs:
      spawn_pinch_right:
        car_0:
        - -45.569
        - -1.0
        - 0.2
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_left:
        car_0:
        - -45.569
        - -0.4
        - -0.2
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_pinch_ahead:
        car_0:
        - -45.569
        - -0.7
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_approach_0.0C:
        car_0:
        - -49.269
        - -0.7
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_approach_0.3L:
        car_0:
        - -49.269
        - -0.4
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0
      spawn_approach_0.3R:
        car_0:
        - -49.269
        - -1.0
        - 0.0
        car_1:
        - -46.769
        - -0.7
        - 0.0

  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0

agents:
  car_0:
    role: attacker
    algorithm: ppo
    target_id: car_1
    params:
      lr: 0.0003
      gamma: 0.995
      n_steps: 2048
      n_epochs: 10
      gae_lambda: 0.95
      clip_epsilon: 0.2
      entropy_coef: 0.02
      value_loss_coef: 0.5
      max_grad_norm: 0.5
      hidden_dims:
      - 256
      - 256
      batch_size: 256
    observation:
      preset: gaplock
    reward:
      preset: gaplock_full
      overrides:
        forcing:
          enabled: true
          pinch_pockets:
            enabled: true
            anchor_forward: 1.2
            anchor_lateral: 0.35
            sigma: 0.55
            weight: 0.004
            peak: 1.0
            floor: -0.5
            power: 2.0
          clearance:
            enabled: true
            weight: 0.003
            band_min: 0.3
            band_max: 3.2
            clip: 0.015
            time_scaled: true
          turn:
            enabled: true
            weight: 0.006
            clip: 0.015
            time_scaled: true
        distance:
          enabled: false
        heading:
          enabled: true
          coefficient: 0.001
        speed:
          enabled: true
          bonus_coef: 0.0005
        step_reward: -0.001
        terminal:
          target_crash: 200.0
          self_crash: -20.0
          timeout: -100.0
          collision: 0.0

  car_1:
    role: defender
    algorithm: ftg
    params:
      max_distance: 12.0
      window_size: 4
      bubble_radius: 2.0  # Will be overridden by curriculum
      max_steer: 0.42
      min_speed: 0.2
      max_speed: 1.0
      steering_gain: 0.25  # Will be overridden by curriculum
      fov: 4.71238898
      normalized: false
      steer_smooth: 0.6
      mode: lidar
      gap_min_range: 0.4
      target_mode: center
      wall_avoid_kick: 0.02
      panic_factor_near: 1.0
      panic_factor_very_near: 1.0
      use_disparity_extender: true
      disparity_threshold: 0.35
      vehicle_width: 0.225
      safety_margin: 0.08

# Phased Curriculum Configuration
curriculum:
  type: phased
  start_phase: 0  # Can override to start from later phase

  phases:
    # ========================================================================
    # PHASE 1: Foundation - Learn basics against weak, locked-speed defender
    # ========================================================================
    - name: "1_foundation"
      description: "Learn basic attack patterns against stationary-speed defender"
      criteria:
        success_rate: 0.70
        avg_reward: 50.0
        min_episodes: 50
        patience: 300
        window_size: 100
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.44, 0.44]
      lock_speed_steps: 800
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
        safety_margin: 0.05
        gap_min_range: 0.4
        panic_factor_near: 1.0
        panic_factor_very_near: 1.0

    # ========================================================================
    # PHASE 2: Speed Lock Reduction - Defender can adjust speed mid-episode
    # ========================================================================
    - name: "2a_reduce_lock_600"
      description: "Reduce speed lock to 600 steps"
      criteria:
        success_rate: 0.65
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.44, 0.44]
      lock_speed_steps: 600
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
        safety_margin: 0.05

    - name: "2b_reduce_lock_400"
      description: "Reduce speed lock to 400 steps"
      criteria:
        success_rate: 0.65
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.44, 0.44]
      lock_speed_steps: 400
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
        safety_margin: 0.05

    - name: "2c_reduce_lock_200"
      description: "Reduce speed lock to 200 steps"
      criteria:
        success_rate: 0.65
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.44, 0.44]
      lock_speed_steps: 200
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
        safety_margin: 0.05

    # ========================================================================
    # PHASE 3: Speed Variation - Handle different defender speeds
    # ========================================================================
    - name: "3a_speed_narrow"
      description: "Tight speed variation around optimal"
      criteria:
        success_rate: 0.60
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.42, 0.46]
      lock_speed_steps: 100
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
        safety_margin: 0.05

    - name: "3b_speed_medium"
      description: "Medium speed range"
      criteria:
        success_rate: 0.55
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.35, 0.55]
      lock_speed_steps: 100
      ftg:
        steering_gain: 0.25
        bubble_radius: 2.0
        safety_margin: 0.06

    - name: "3c_speed_wide"
      description: "Wide speed range"
      criteria:
        success_rate: 0.50
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        speed_range: [0.30, 0.70]
      lock_speed_steps: 50
      ftg:
        steering_gain: 0.30
        bubble_radius: 2.2
        safety_margin: 0.07

    # ========================================================================
    # PHASE 4: Spatial Variation - Different geometric scenarios
    # ========================================================================
    - name: "4a_add_ahead"
      description: "Add pinch ahead scenario"
      criteria:
        success_rate: 0.50
        min_episodes: 50
        patience: 250
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        - spawn_pinch_ahead
        speed_range: [0.30, 0.70]
      lock_speed_steps: 50
      ftg:
        steering_gain: 0.30
        bubble_radius: 2.2
        safety_margin: 0.07

    - name: "4b_add_approach"
      description: "Add approach scenarios"
      criteria:
        success_rate: 0.45
        min_episodes: 50
        patience: 300
      spawn:
        points:
        - spawn_pinch_right
        - spawn_pinch_left
        - spawn_pinch_ahead
        - spawn_approach_0.0C
        - spawn_approach_0.3L
        - spawn_approach_0.3R
        speed_range: [0.30, 0.80]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.32
        bubble_radius: 2.4
        safety_margin: 0.08

    - name: "4c_all_spawns"
      description: "All spawn positions"
      criteria:
        success_rate: 0.40
        min_episodes: 75
        patience: 350
      spawn:
        points: all
        speed_range: [0.30, 1.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.35
        bubble_radius: 2.5
        safety_margin: 0.08

    # ========================================================================
    # PHASE 5: FTG Resistance - Increasingly competent defender
    # ========================================================================
    - name: "5a_ftg_moderate"
      description: "Moderate FTG resistance"
      criteria:
        success_rate: 0.35
        min_episodes: 100
        patience: 400
      spawn:
        points: all
        speed_range: [0.30, 1.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.40
        bubble_radius: 2.7
        safety_margin: 0.10
        gap_min_range: 0.50
        panic_factor_near: 1.1
        panic_factor_very_near: 1.2

    - name: "5b_ftg_strong"
      description: "Strong FTG resistance"
      criteria:
        success_rate: 0.30
        min_episodes: 100
        patience: 400
      spawn:
        points: all
        speed_range: [0.30, 1.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.50
        bubble_radius: 3.0
        safety_margin: 0.12
        gap_min_range: 0.60
        target_mode: farthest
        panic_factor_near: 1.2
        panic_factor_very_near: 1.3
        wall_avoid_kick: 0.08

    - name: "5c_ftg_expert"
      description: "Expert FTG resistance - final challenge"
      criteria:
        success_rate: 0.25
        min_episodes: 150
        patience: 500
      spawn:
        points: all
        speed_range: [0.30, 1.0]
      lock_speed_steps: 0
      ftg:
        steering_gain: 0.60
        bubble_radius: 3.5
        safety_margin: 0.15
        gap_min_range: 0.65
        target_mode: farthest
        panic_factor_near: 1.3
        panic_factor_very_near: 1.5
        wall_avoid_kick: 0.12

wandb:
  enabled: true
  project: marl-f110
  entity: ahoop004-old-dominion-university
  tags:
  - ppo
  - phased_curriculum
  - gaplock
  notes: "PPO with progressive phased curriculum: foundation → speed_lock_reduction → speed_variation → spatial_variation → ftg_resistance"
