# Minimal test scenario for WaveletEpisodicAgent
# For quick local testing without curriculum or wandb

experiment:
  name: test_wavelet_episodic
  episodes: 50  # Short test run
  seed: 42
  normalize_observations: false

environment:
  map: maps/line2/line2.yaml
  num_agents: 1  # Single agent for testing
  max_steps: 1000
  lidar_beams: 108
  spawn_points:
  - spawn_2
  timestep: 0.01
  render: false
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    length: 0.32
    width: 0.225
    m: 3.74
    I: 0.04712
    s_min: -0.46
    s_max: 0.46
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 0.8
    a_max: 2.0
    v_min: -1.0
    v_max: 1.0

agents:
  car_0:
    role: solo
    algorithm: wavelet_episodic
    params:
      # Chunk parameters
      chunk_size: 25
      chunk_stride: 12
      grid_shape: [5, 5]

      # Buffers (smaller for testing)
      chronological_buffer:
        max_capacity: 5000
      episodic_buffer:
        capacity: 500
        selection_mode: "uniform"

      # Wavelet
      wavelet:
        type: "haar"
        mode: "symmetric"

      # Encoder (smaller for faster testing)
      encoder:
        latent_dim: 64
        cnn:
          channels: [16, 32, 64]
          pooling: [2, 2, null]
        rnn:
          use: true
          type: "lstm"
          hidden_size: 128
          num_layers: 1
          dropout: 0.0

      # Loss weights
      loss_weights:
        policy: 1.0
        value: 0.5
        reconstruction: 0.1
        forward: 0.1

      # Optimization
      learning_rate: 3.0e-4
      batch_size: 16
      warmup_chunks: 50
      update_freq: 4
      gamma: 0.99

      # Action bounds
      action_low: [-0.46, -1.0]
      action_high: [0.46, 1.0]

      # Device
      device: "cpu"  # Use CPU for testing

    observation:
      preset: original  # Simple observation

    reward:
      preset: progress  # Simple progress-based reward

wandb:
  enabled: false  # No wandb for local testing
