env:
  seed: 42
  n_agents: 2
  max_steps: 5000
  timestep: 0.01
  integrator: 'RK4'

  map_dir: "maps"
  map_yaml: "Shanghai_map.yaml"
  map: 'Shanghai_map.yaml'
  map_ext: .png
  render_mode: 'human'
  # TODO: include explicit map_image relative path once assets are standardized, enabling renderer cache priming.



  lidar_beams: 108
  lidar_range: 30.0
  lidar_dist: 0.0
  start_thresh: 0.5
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    m: 3.74
    I: 0.04712
    s_min: -0.4189
    s_max: 0.4189
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 7.319
    a_max: 9.51
    v_min: -5.0
    v_max: 20.0
    width: 0.31
    length: 0.58
  
  start_poses:
    - [0.0, 0.0, 0.0]
    # - [1.5, 0.5, 0.0]
    # - [2.0, 0.0, 0.0]
    - [3.0, 0.5, 0.0]    
