env:
  seed: 42
  n_agents: 2
  max_steps: 2500
  timestep: 0.01
  integrator: 'RK4'
  render_interval: 0
  update: 2
  vehicle_params:
    v_min: -2.0
    v_max: 10.0

  map_dir: "maps"
  map_yaml: "Shanghai_map.yaml"
  map: 'Shanghai_map.yaml'
  map_ext: .png
  render_mode: 'human'

  start_poses:
    - [0.0, 0.0, 0.0]
    - [3.0, 0.5, 0.0]

agents:
  roster:
    - algo: dqn
      slot: 0
      role: attacker
      config_ref: dqn
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            target_role: defender
    - algo: follow_gap
      slot: 1
      role: defender

reward:
  alive_bonus: 0.00008
  forward_scale: 0.002
  reverse_penalty: 0.005
  lateral_penalty: 0.0006
  target_distance_scale: 0.0015
  target_wall_bonus: 0.00004
  self_wall_penalty: 0.00004
  herd_bonus: 0.12
  ego_collision_penalty: -0.40
  opponent_collision_bonus: 0.08
  herd_position_radius: 3.5
  herd_position_slack: 1.0
  herd_position_scale: 0.00007
  herd_angle_scale: 0.00005
  herd_angle_power: 2.0
  spin_thresh: 0.6
  spin_penalty: 0.25
  spin_speed_gate: 0.3
  spin_dwell_steps: 5
  spin_step_cap: 0.00015
  spin_episode_cap: 0.04
  spin_grace_steps: 20
  spin_alpha: 0.2
  dt: 0.01

dqn:
  lr: 0.0005
  gamma: 0.99
  batch_size: 128
  buffer_size: 50000
  target_update_interval: 50
  epsilon_start: 1
  epsilon_end: 0.1
  epsilon_decay_rate: 0.9995
  hidden_dims: [256, 256]
  action_set:
    - [-0.35, 2.5]
    - [0.0, 2.5]
    - [0.35, 2.5]
    - [-0.25, 5.5]
    - [0.0, 5.5]
    - [0.25, 5.5]
    - [-0.15, 8.0]
    - [0.0, 8.0]
    - [0.15, 8.0]
    - [-0.10, 10.0]
    - [0.0, 10.0]
    - [0.10, 10.0]
    - [0.0, 0.0]
  train_episodes: 5000
  eval_episodes: 5
  save_dir: checkpoints/
  checkpoint_name: dqn_gaplock.pt

main:
  mode: train_eval
  wandb:
    enabled: true
    project: marl-f110
    entity: null
    group: dqn
    tags:
      - gaplock
      - dqn
  tensorboard_dir: runs/
  save_eval_rollouts: true
  eval_rollout_dir: eval_rollouts/
  checkpoint: checkpoints/dqn_gaplock.pt
  train_episodes: 5000
  eval_episodes: 5
