env:
  seed: 42
  n_agents: 2
  max_steps: 1500
  timestep: 0.01
  integrator: 'RK4'
  render_interval: 0
  update: 1

  map_dir: "maps"
  map_yaml: "Shanghai_map.yaml"
  map: 'Shanghai_map.yaml'
  map_ext: .png
  render_mode: 'human'

  start_poses:
    - [0.0, 0.0, 0.0]
    - [3.0, 0.5, 0.0]

agents:
  roster:
    - algo: ppo
      slot: 0
      role: attacker
      config_ref: ppo
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            target_role: defender
    - algo: follow_gap
      slot: 1
      role: defender

reward:
  alive_bonus: 0.05
  forward_scale: 0.12
  reverse_penalty: 2.0
  lateral_penalty: 0.1
  target_distance_scale: 0.25
  target_wall_bonus: 1.0
  self_wall_penalty: 0.2
  herd_bonus: 200.0
  ego_collision_penalty: -80.0
  opponent_collision_bonus: 150.0
  spin_penalty: 2.0
  spin_thresh: 0.4

ppo:
  actor_lr: 0.0003
  critic_lr: 0.0005
  gamma: 0.99
  lam: 0.95
  ent_coef: 0.01
  clip_eps: 0.2
  update_epochs: 10
  minibatch_size: 64
  train_episodes: 500
  eval_episodes: 5
  save_dir: checkpoints/
  checkpoint_name: ppo_gaplock.pt

main:
  mode: train_eval
  wandb:
    enabled: true
    project: marl-f110
    entity: null
    tags:
      - gaplock
      - ppo
  tensorboard_dir: runs/
  save_eval_rollouts: true
  eval_rollout_dir: eval_rollouts/
  checkpoint: checkpoints/ppo_gaplock.pt
  train_episodes: 500
  eval_episodes: 5
