env:
  seed: 123
  n_agents: 2
  max_steps: 1500
  timestep: 0.01
  integrator: 'RK4'
  render_interval: 0
  update: 1

  map_dir: "maps"
  map_yaml: "Shanghai_map.yaml"
  map: 'Shanghai_map.yaml'
  map_ext: .png
  render_mode: 'human'

  lidar_beams: 1080
  lidar_range: 30.0
  start_thresh: 0.5
  vehicle_params:
    mu: 1.0489
    C_Sf: 4.718
    C_Sr: 5.4562
    lf: 0.15875
    lr: 0.17145
    h: 0.074
    m: 3.74
    I: 0.04712
    s_min: -0.4189
    s_max: 0.4189
    sv_min: -3.2
    sv_max: 3.2
    v_switch: 7.319
    a_max: 9.51
    v_min: -5.0
    v_max: 10.0
    width: 0.31
    length: 0.58

  start_poses:
    - [0.0, 0.0, 0.0]
    - [3.0, 0.5, 0.0]

agents:
  roster:
    - algo: td3
      slot: 0
      role: attacker
      config_ref: td3
      wrappers:
        - factory: obs
          params:
            max_scan: 30.0
            normalize: true
            target_role: defender
    - algo: follow_gap
      slot: 1
      role: defender

reward:
  alive_bonus: 0.05
  forward_scale: 0.1
  reverse_penalty: 2.0
  lateral_penalty: 0.1
  target_distance_scale: 0.2
  target_wall_bonus: 1.0
  self_wall_penalty: 0.2
  herd_bonus: 200.0
  ego_collision_penalty: -80.0
  spin_penalty: 2.0
  spin_thresh: 0.4

td3:
  actor_lr: 0.0005
  critic_lr: 0.0008
  gamma: 0.99
  tau: 0.005
  policy_noise: 0.3
  noise_clip: 0.5
  policy_delay: 2
  batch_size: 128
  buffer_size: 50000
  warmup_steps: 1000
  exploration_noise: 0.15
  hidden_dims: [256, 256]
  save_dir: checkpoints/
  checkpoint_name: td3_gaplock.pt

main:
  mode: train
  wandb:
    enabled: true
    project: marl-f110
    entity: null
    tags:
      - gaplock
      - td3
  tensorboard_dir: runs/
  save_eval_rollouts: false
  eval_rollout_dir: eval_rollouts/
  checkpoint: checkpoints/td3_gaplock.pt
  train_episodes: 500
