# Sweep definitions for TD3 low-data experiments.
base:
  algo: td3_starved
  repeat: 1
  auto_seed: true
  seed_base: 42
  seed_step: 7
  wandb_prefix: td3-starved-
  main_args:
    - --log-level
    - info
  extra_main_args:
    - --track-metrics
  env:
    render_interval: 0

matrix:
  td3_starved.actor_lr: [0.0003, 0.0004]
  td3_starved.critic_lr: [0.0010, 0.0012]
  td3_starved.policy_noise: [0.2, 0.25]
  td3_starved.gradient_steps: [2, 3]
  td3_starved.exploration_noise_decay_steps: [50000, 75000]

runs:
  - algo: td3_starved
    td3_starved.actor_lr: 0.00035
    td3_starved.critic_lr: 0.0011
    td3_starved.policy_noise: 0.22
    td3_starved.gradient_steps: 3
    td3_starved.exploration_noise_decay_steps: 60000
    wandb_prefix: td3-starved-focus-
    repeat: 3
