# Policy layer for discrete DQN attackers.

agent:
  algo: dqn
  config: algorithms/dqn.yaml
  wrappers:
    - factory: obs
      params:
        max_scan: 30.0
        normalize: true
        target_role: defender
