# Policy layer for PPO attackers.

agent:
  algo: ppo
  config: algorithms/ppo.yaml
  wrappers:
    - factory: obs
      params:
        max_scan: 30.0
        normalize: true
        target_role: defender
